import {writeFile,mkdir} from 'node:fs/promises';
import {defaults,fundingTable,unlockSchedule,VERSION} from '../src/model.js';
import {initialLiquidityAudit,sizeLiquidity} from '../src/market.js';
import {runStress,SCENARIOS} from '../src/stress.js';
import {runAttackSuite} from '../src/attacks.js';
import {launchReadiness,unlockPressureAudit} from '../src/analysis.js';
import {defaultCurveLabConfig} from '../src/curve-sim-config.js';
import {runCurveSimulation,exportNetworkCSV,exportTransactionsCSV,exportMarkdownReport} from '../src/curve-simulation.js';
import {optimizeCurveConfig,exportCandidatesCSV} from '../src/curve-optimizer.js';
const c=defaults();c.stress.paths=100;c.stress.months=36;
await mkdir('examples',{recursive:true});await mkdir('reports',{recursive:true});
const save=async(p,x)=>writeFile(p,JSON.stringify(x,null,2)+'\n');
const csv=(rows,cols)=>[cols.join(','),...rows.map(r=>cols.map(k=>{const v=r[k];return typeof v==='number'?String(v):JSON.stringify(v??'');}).join(','))].join('\n')+'\n';
const csvRows=rows=>rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')+'\n';
const audit=initialLiquidityAudit(c),sizing=sizeLiquidity(c),attacks=runAttackSuite(c);
const base=runStress(c);const crisis=runStress(c,SCENARIOS.find(x=>x.id==='combined').changes);
const curveConfig=defaultCurveLabConfig(c);curveConfig.horizonDays=180;curveConfig.participants.initial=300;curveConfig.totalInitialParticipants=300;curveConfig.totalInitialCapitalCCLX=300000;
const curveBase=runCurveSimulation(curveConfig,{seed:curveConfig.seed});
const curveOptimizer=optimizeCurveConfig(curveConfig,{budget:20,selectionSeeds:[101,102],validationSeeds:[901]});
const readiness=launchReadiness(c,base,attacks);
const report={version:VERSION,asOf:'2026-09-09',data:'Entirely synthetic, not calibrated to live market data or verified project accounts.',assumptions:c,launch:{audit,sizing},base,combinedCrisis:crisis,curveLab:{config:curveConfig,base:curveBase,optimizer:curveOptimizer},attacks,readiness};
await save('examples/default-assumptions.json',c);
await save('examples/sample-results.json',{version:VERSION,launch:{audit,sizing},base:{meta:base.meta,summary:base.summary},combinedCrisis:{meta:crisis.meta,summary:crisis.summary},attacks:{passed:attacks.passed,failed:attacks.failed,unverified:attacks.unverified},readiness});
await save('reports/reproducible-simulation.json',report);
await writeFile('examples/unlock-schedule.csv',csv(unlockSchedule(c,60),['month','liquid','restricted','governed','rewardCeiling','liquidDelta','restrictedDelta','scheduledSellTokens']));
await writeFile('examples/unlock-pain-zones.csv',csv(unlockPressureAudit(c,60),['month','unlocked','restricted','rewardCeiling','expectedSell','pressure','depth','coverage','requiredDepth','gap']));
await writeFile('examples/monte-carlo-pain-zones.csv',csv(base.series,['month','failProbability','unlockFailProbability','queueProbability','zone']));
await save('examples/funding-table.json',fundingTable(c));
await save('examples/curve-sample-results.json',{config:curveConfig,summary:curveBase.summary,feeAccounts:curveBase.feeAccounts,warnings:curveBase.warnings});
await writeFile('examples/curve-network-series.csv',csvRows(exportNetworkCSV(curveBase)));
await writeFile('examples/curve-transactions.csv',csvRows(exportTransactionsCSV(curveBase)));
await writeFile('examples/optimization-candidates.csv',csvRows(exportCandidatesCSV(curveOptimizer)));
await writeFile('reports/curve-lab-report.md',exportMarkdownReport(curveBase));
const text=`# CCLX Economic Lab — reproducible synthetic report\n\nModel version: ${VERSION}. 100 seeded paths, 36 monthly steps, seed ${c.stress.seed}. No market or project figures have been independently verified.\n\n## Launch assumptions\n\nQuote funding: $${audit.assignedQuote.toLocaleString()}; CEX $${c.liquidity.cexQuote.toLocaleString()}, DEX $${c.liquidity.dexQuote.toLocaleString()}. MM inventory ${audit.inventory.toLocaleString()} CCLX is not additional cash. 2% bid depth: $${audit.within2.toFixed(0)}. Static launch audit: ${audit.pass?'PASS':'FAIL'}. Minimum proportional liquidity sizing: ${sizing.feasible?'$'+sizing.requiredBudget.toFixed(0):'not feasible'}.\n\n## Monte Carlo\n\nBase median terminal price: $${base.summary.terminalPrice.p50.toFixed(4)}; 5–95%: $${base.summary.terminalPrice.p05.toFixed(4)}–$${base.summary.terminalPrice.p95.toFixed(4)}. Probability of at least one depth-coverage breach: ${(base.summary.depthBreachProbability*100).toFixed(1)}%. Probability of attempted unfunded liquidity replenishment: ${(base.summary.reserveExhaustionProbability*100).toFixed(1)}%. Combined-crisis median terminal price: $${crisis.summary.terminalPrice.p50.toFixed(4)}.\n\nThese are model-conditional outputs, not price forecasts. An unfunded-replenishment event means the modeled market maker attempted to restore cash that was not available; it does not imply a contractual obligation to defend token price.\n\n## Adversarial checks\n\n${attacks.passed} model checks passed, ${attacks.failed} failed, ${attacks.unverified} require external verification. Contract security, legal rights, genuine market-maker commitments and project cash flows have not been validated. Launch readiness: ${readiness.ready?'PASS':'NOT VERIFIED / NOT READY'}.\n\n## Important modeling boundaries\n\nThe current CEX order book is an aggregated synthetic ladder, not a live exchange. The DEX is constant-product; project curves are reserve-backed linear integrals with separate receipt accounting. Monthly flows are approximations and do not constitute a tick-level limit-order-book or agent-based simulation. Price, order flow and project risks must be calibrated before interpreting probabilities. Restricted CO2BIT principal and rewards remain non-transferable; they do not become ordinary circulating supply through vesting. The ordinary team allocation is distinct from the restricted internal capacity. Token funding is not an equity cap table.\n\nSee the JSON files for all numerical assumptions and outputs; CSV files provide the unlock and pain-zone series.\n`;
await writeFile('reports/RESULTS.md',text.replace('## Monte Carlo','## Financial Simulation'));
console.log(JSON.stringify({version:VERSION,base:{median:base.summary.terminalPrice.p50,depthBreach:base.summary.depthBreachProbability,reserveExhaustion:base.summary.reserveExhaustionProbability},crisis:{median:crisis.summary.terminalPrice.p50},attackChecks:attacks.passed,unverified:attacks.unverified,ready:readiness.ready},null,2));
