import {VERSION,defaults,clone,fmt,usd,pct,div,sum,validate,fundingTable,unlockSchedule,bridgeQuote,poolEconomics,allocation,initialFloat,buckets,REWARD_BUDGET} from './model.js';
import {newMock,mockAction,mockMetrics} from './mock.js';
import {newVault,curveQuote,curveSpot,curveAudit} from './curve.js';
import {makeMarket,executeSell,executeBuy,marketDepth,depthLadder,initialLiquidityAudit,sizeLiquidity,maximumExecutable} from './market.js';
import {runAttackSuite,adversarialEconomics} from './attacks.js';
import {liquidityFrontier,priceDepthGrid,unlockPressureAudit,launchReadiness,sensitivity} from './analysis.js';
import {parseOrderBookCSV,analyzeSnapshot} from './calibration.js';
import {SCENARIOS} from './stress.js';
import {defaultCurveLabConfig,condensedV5Config,CURVE_LAB_SCENARIOS,mergeCurveLabConfig,validateCurveConfig,PARAMETER_REGISTER} from './curve-sim-config.js';
import {materializeCurveProjects,makeVault,phaseForProject,quoteDeposit,quoteWithdrawal,quoteMigration,exportNetworkCSV,exportTransactionsCSV,exportMarkdownReport} from './curve-simulation.js';
import {curveSeries} from './curve-families.js';
import {exportCandidatesCSV,DEFAULT_SEARCH_SPACE,DEFAULT_CONSTRAINTS} from './curve-optimizer.js';

const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const F=(n,d=0)=>fmt(n,d), U=(n,d=0)=>usd(n,d), P=(n,d=1)=>pct(n,d), M=n=>Math.abs(n)>=1e9?F(n/1e9,2)+'B':Math.abs(n)>=1e6?F(n/1e6,2)+'M':Math.abs(n)>=1e3?F(n/1e3,1)+'k':F(n,2);
let config=defaults();try{const saved=JSON.parse(localStorage.getItem('cclx-lab-config')||'null');if(saved&&!validate(saved).length)config=saved;}catch{}
const state={page:'overview',mock:newMock(config),stress:null,scenario:'base',running:false,progress:0,runKind:'',attacks:null,imported:null,quoteAmount:100000,quoteSide:'sell',projectId:'forest',mockAmount:1000,mockSide:'buy',mockRestricted:false,months:60,chart:'price',selectedMonth:12,error:'',notice:'',worker:null,dirty:false,rawJSON:'',editor:'',sidebar:false,curveConfig:defaultCurveLabConfig(config),curveResult:null,curveOptimizer:null,curveScenario:'no_flow',curveTab:'overview',curveProjectId:'forest',curveQuoteAmount:10000,curveWithdrawalShares:5000};
const NAV=[['overview','Overview','◫','Workspace'],['mock','Mock application','▦','01 / Product'],['curve-lab','Bonding Curve Lab','⌬','01 / Product'],['liquidity','Launch liquidity','◈','02 / Economic lab'],['funding','Funding & unlocks','▤','02 / Economic lab'],['stress','Monte Carlo','⌁','02 / Economic lab'],['exploits','Exploit laboratory','◇','02 / Economic lab'],['calibration','Market calibration','≋','02 / Economic lab'],['assumptions','Assumptions & gates','⚙','03 / Controls']];
const titles=Object.fromEntries(NAV.map(n=>[n[0],n[1]]));
const card=(title,body,sub='',extra='')=>`<section class="card card-pad ${extra}"><div class="card-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div></div>${body}</section>`;
const metric=(label,value,note='',tone='')=>`<div class="card card-pad"><div class="metric-label">${label}</div><div class="metric-value ${tone}">${value}</div><div class="metric-note">${note}</div></div>`;
const badge=(text,tone='green')=>`<span class="badge ${tone}">${esc(text)}</span>`;
const notice=(txt,tone='amber')=>`<div class="notice ${tone}"><span class="notice-icon">${tone==='red'?'!':'i'}</span><div>${txt}</div></div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${v??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const btn=(label,action,cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}">${label}</button>`;
const input=(label,path,value,step=1,note='',min=0)=>`<div class="field"><label>${label}</label><input type="number" data-config="${path}" value="${Number(value)}" step="${step}" min="${min}">${note?`<small>${note}</small>`:''}</div>`;
const select=(label,id,values,value)=>`<div class="field"><label>${label}</label><select id="${id}">${values.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`;
const kv=(rows)=>`<div class="kv-list">${rows.map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div>`;
function title(h,sub,eyebrow='CCLX / ECONOMIC LAB',actions=''){return `<div class="page-title"><div><div class="eyebrow">${eyebrow}</div><h1>${h}</h1><p>${sub}</p></div><div class="actions">${actions}</div></div>`;}
const colours={green:'#326f58',blue:'#446fbd',amber:'#b78436',red:'#b85c54',purple:'#8069a8',gray:'#93a09a'};
function chart(series,{height=245,ymin=null,ymax=null,labels=[],format=v=>M(v),zero=false}={}){
 const all=series.flatMap(s=>s.values.filter(Number.isFinite));if(!all.length)return '<div class="empty">No data available.</div>';
 let lo=ymin??Math.min(...all),hi=ymax??Math.max(...all);if(zero)lo=Math.min(0,lo);if(hi===lo)hi=lo+1;const pad=(hi-lo)*.08;hi+=pad;lo-=pad;
 const W=850,H=height,pl=62,pr=20,pt=18,pb=37,iw=W-pl-pr,ih=H-pt-pb;
 const x=i=>pl+(i/(Math.max(1,Math.max(...series.map(s=>s.values.length))-1)))*iw,y=v=>pt+(hi-v)/(hi-lo)*ih;
 const line=s=>s.values.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(v).toFixed(2)}`).join(' ');
 let out=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(series.map(s=>s.name).join(', '))}">`;
 for(let i=0;i<=4;i++){let yy=pt+i*ih/4;out+=`<line class="grid" x1="${pl}" y1="${yy}" x2="${W-pr}" y2="${yy}"/><text x="${pl-8}" y="${yy+3}" text-anchor="end">${esc(format(hi-(hi-lo)*i/4))}</text>`;}
 for(let i=0;i<=4;i++){let xx=pl+i*iw/4;out+=`<text x="${xx}" y="${H-9}" text-anchor="middle">${esc(labels[Math.round(i*(labels.length-1)/4)]??Math.round(i*(Math.max(...series.map(s=>s.values.length))-1)/4))}</text>`;}
 for(const s of series){out+=`<path d="${line(s)}" class="line" stroke="${s.color||colours.green}" stroke-width="2.5"/>`;if(s.values.length<80)out+=s.values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="2.5" fill="${s.color||colours.green}"><title>${esc(s.name)}: ${esc(format(v))}</title></circle>`).join('');}
 return out+'</svg>'+`<div class="legend">${series.map(s=>`<span><i style="background:${s.color||colours.green}"></i>${esc(s.name)}</span>`).join('')}</div>`;
}
function bandChart(rows,key,format=v=>M(v)){
 if(!rows?.length)return '';
 const a=rows.map(r=>r[key]?.p05??r[key]),b=rows.map(r=>r[key]?.p50??r[key]),c=rows.map(r=>r[key]?.p95??r[key]);
 return chart([{name:'P05',values:a,color:colours.amber},{name:'Median',values:b,color:colours.green},{name:'P95',values:c,color:colours.blue}],{labels:rows.map(r=>'M'+r.month),format});
}
function progress(n,max=1,color='green'){return `<div class="progress-track"><div class="progress-fill ${color}" style="width:${Math.min(100,Math.max(0,n/max*100))}%"></div></div>`;}
function checksView(checks){return checks.map(c=>`<div class="check-row"><div class="check-mark ${c.status==='unverified'?'unverified':c.pass?'pass':'fail'}">${c.status==='unverified'?'?':c.pass?'✓':'×'}</div><div><div class="check-name">${esc(c.name)}</div><div class="check-detail">${esc(c.detail)}</div>${c.category?`<div class="check-category">${esc(c.category)}</div>`:''}</div></div>`).join('');}
function save(){try{localStorage.setItem('cclx-lab-config',JSON.stringify(config));}catch{}state.dirty=true;state.stress=null;state.attacks=null;state.imported=null;}
function get(path){return path.split('.').reduce((o,k)=>o?.[k],config);}
function set(path,value){const next=clone(config),keys=path.split('.');let o=next;for(const k of keys.slice(0,-1))o=o[k];o[keys.at(-1)]=value;const errors=validate(next);if(errors.length)throw Error(errors.join('; '));config=next;invalidate();}
function download(name,text,type='text/plain'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csv=(rows)=>rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');
function makeWorker(){return new Worker('/src/worker.js',{type:'module'});}
function getDeep(obj,path){return path.split('.').reduce((o,k)=>o?.[k],obj);}
function setDeep(obj,path,value){const keys=path.split('.');let o=obj;for(const k of keys.slice(0,-1)){o[k]??={};o=o[k];}o[keys.at(-1)]=value;}
function setCurve(path,value){const next=clone(state.curveConfig);setDeep(next,path,value);const errors=validateCurveConfig(next);if(errors.length)throw Error(errors.join('; '));state.curveConfig=next;state.curveResult=null;state.curveOptimizer=null;}
const curveInput=(label,path,value,step=1,note='',min=0)=>`<div class="field"><label>${label}</label><input type="number" data-curve-config="${path}" value="${Number(value)}" step="${step}" min="${min}">${note?`<small>${note}</small>`:''}</div>`;
const curveSelect=(label,path,values,value)=>`<div class="field"><label>${label}</label><select data-curve-select="${path}">${values.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></div>`;
const curveTabs=()=>`<div class="tabs">${[['overview','Overview'],['designer','Curve designer'],['flows','Participants & flows'],['fees','Fees & routing'],['simulation','Simulation'],['optimizer','Sensitivity & optimizer'],['ledger','Ledger & exports']].map(([k,t])=>`<button class="tab ${state.curveTab===k?'active':''}" data-curve-tab="${k}">${esc(t)}</button>`).join('')}</div>`;
function toast(message,error=false){state.notice=message;const el=$('#toast');if(el){el.className='toast '+(error?'error':'success');el.textContent=message;el.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>{el.hidden=true;},5000);}}
function navigate(page){state.page=page;state.sidebar=false;window.location.hash=page;render();window.scrollTo(0,0);}
function shell(){const groups=[...new Set(NAV.map(n=>n[3]))];return `<div class="shell"><aside class="sidebar ${state.sidebar?'open':''}"><div class="side-logo"><div class="brand-mark">C<span style="font-size:10px;align-self:flex-end;margin:0 0 7px 1px">✦</span></div><div><div class="brand-title">CCLX Lab</div><div class="brand-sub">Economic research</div></div></div>${groups.map(g=>`<div class="side-group">${g}</div>${NAV.filter(n=>n[3]===g).map(n=>`<button class="nav-link ${state.page===n[0]?'active':''}" data-nav="${n[0]}"><span class="nav-icon">${n[2]}</span>${n[1]}</button>`).join('')}`).join('')}<div class="side-bottom"><div class="side-rule"></div><span class="side-dot"></span><strong>Local simulation</strong><br>No live orders or wallets.<br>v${VERSION} · Research only</div></aside><div class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="btn mobile-menu" data-action="menu" aria-label="Open navigation">☰</button><div class="breadcrumb">Workspace / <strong>${titles[state.page]}</strong></div></div><div class="top-actions">${badge('SYNTHETIC DATA','blue')}<span class="hide-mobile" style="font-size:11px;color:var(--muted)">No exchange connection</span>${btn('Export config','export-config','small')}<div class="avatar">CL</div></div></header><main class="content" id="page">${pages[state.page]()}</main></div></div><div id="toast" class="toast" hidden></div>${state.running?`<div class="progress-overlay card"><div class="card-head"><h3>Running simulations</h3><span>${F(state.progress*100)}%</span></div>${progress(state.progress)}<p class="card-sub">The calculation runs in a separate worker so the interface stays responsive.</p>${btn('Cancel run','cancel','small')}</div>`:''}`;}

function overview(){const audit=initialLiquidityAudit(config),pool=poolEconomics(config),b=bridgeQuote(config),errors=validate(config);return title('A product prototype and a quantitative lab','Explore the CCLX user journey, then challenge every liquidity, vesting and economic assumption. All values are illustrative, editable and explicitly unverified.','WORKSPACE / OVERVIEW',btn('Run launch audit','go-liquidity','primary'))+
notice('This is a research model, not a live protocol or investment recommendation. The supplied tokenomics are working proposals; market prices, revenue, liquidity and risk parameters are dummy inputs. A model pass is not launch approval.','blue')+
`<div class="grid g4">${metric('Maximum token supply',M(config.supply)+' CCLX','Fixed working ceiling')}${metric('Reference launch FDV',U(config.supply*config.launchPrice),'Not a company equity valuation')}${metric('Initial quote funding',U(audit.assignedQuote),'CEX + DEX cash; inventory excluded')}${metric('Initial 2% bid depth',U(audit.within2),'Synthetic marginal-price depth')}</div>`+
`<div class="section-label">01 / Product experience <span class="subtle">Click through a realistic mock application</span></div><div class="grid g3">${card('Acquire and allocate',`<div class="flow"><div class="flow-node"><div class="flow-number">01</div><div class="flow-title">Buy CCLX</div><div class="flow-text">Mock execution against finite CEX and DEX liquidity.</div></div><div class="flow-arrow">→</div><div class="flow-node"><div class="flow-number">02</div><div class="flow-title">Select project</div><div class="flow-text">Different project economics, curves and risk parameters.</div></div></div><div class="page-actions">${btn('Open mock app','go-mock','primary')}</div>`,'','span2')}${card('Project returns',`<div class="kv-list">${pool.map(p=>`<div><span>${esc(p.name)}</span><strong>${P(p.totalAPR)}</strong></div>`).join('')}</div><p class="source-note">Indicative combined APR = cash yield + capped bootstrap emissions; not guaranteed.</p>`)}</div>`+
`<div class="section-label">02 / Economic laboratory <span class="subtle">Test feasibility before launch</span></div><div class="grid g3">${card('Market depth',`<div class="metric-value">${U(audit.within2)}</div><p class="card-sub">Initial executable bid notional within 2%. Test order sizes, market depth and funding requirements.</p>${btn('Liquidity audit →','go-liquidity')}`)}${card('Unlock pain zones',`<div class="metric-value">${M(sum(config.rounds.map(r=>r.tokens)))} <small>CCLX</small></div><p class="card-sub">Five financing rounds. Map their cliff releases against finite executable depth.</p>${btn('Vesting & unlocks →','go-funding')}`)}${card('Stochastic stress',`<div class="metric-value">${config.stress.paths} <small>paths</small></div><p class="card-sub">Correlated price and revenue shocks, defaults, finite arbitrage, MM withdrawals and cash-limited replenishment.</p>${btn('Monte Carlo →','go-stress')}`)}</div>`+
`<div class="section-label">03 / Controls and source discipline</div><div class="grid g2">${card('Restricted CO2BIT conversion',kv([['Working value ceiling',U(b.value)],['Maximum restricted allocation',M(b.cap)+' CCLX'],['Illustrative conversion ratio',F(b.ratio,2)+':1'],['Market-sale entitlement','None']])+'<p class="source-note">The legacy capacity is inside the 18% Team & Founders allocation. It must be disclosed as a material sub-allocation, not hidden from investors.</p>')}${card('What the lab cannot establish',checksView([{name:'Market data',detail:'No live, independently verified order book or MM mandate.',status:'unverified'},{name:'Cash flows',detail:'No audited project revenue, reserves or contractual rights.',status:'unverified'},{name:'Contract security',detail:'No deployed contracts or independent smart-contract audit.',status:'unverified'}]))}</div>`+(errors.length?notice(errors.map(esc).join('<br>'),'red'):'');}

function mock(){const w=state.mock.wallet,metrics=mockMetrics(state.mock,config),p=config.projects.find(x=>x.id===state.projectId),v=state.mock.vaults[p.id],econ=metrics.pools.find(x=>x.id===p.id),buy=executeBuy(state.mock.market,Math.max(0,state.mockAmount)),sell=executeSell(state.mock.market,Math.max(0,state.mockAmount)),b=metrics.bridge,positions=metrics.positions;
let quote='';try{if(state.mockSide==='buy')quote=kv([['Estimated CCLX received',M(buy.tokens)],['Executed quote',U(buy.spent,2)],['Average execution price',U(buy.average,5)],['Estimated slippage',P(buy.slippage,2)]]);else if(state.mockSide==='sell')quote=kv([['Estimated proceeds',U(sell.quote,2)],['Tokens executable',M(sell.filled)],['Unfilled quantity',M(sell.unfilled)],['Estimated slippage',P(sell.slippage,2)]]);else if(state.mockSide==='convert')quote=kv([['Conversion ratio',F(b.ratio,2)+':1'],['Restricted CCLX',M(state.mockAmount/b.ratio)],['Transfer / sale rights','None']]);else if(state.mockSide==='allocate')quote=kv(Object.entries(curveQuote(v,Math.max(0,state.mockAmount),'deposit')).filter(([k])=>['shares','fee','spotAfter'].includes(k)).map(([k,val])=>[k,F(val,4)]));}catch(e){quote=notice(esc(e.message),'red');}
return title('Application sandbox','A functional, local-only product prototype. All balances and transactions are fictitious. No blockchain, wallet connection or payment is involved.','01 / PRODUCT EXPERIENCE',btn('Reset demo','reset-mock'))+
`<div class="grid g4">${metric('Mock USD balance',U(w.usd,2),'Spendable simulation cash')}${metric('Unrestricted CCLX',M(w.liquid),'Eligible for a simulated sale')}${metric('Restricted CCLX',M(w.restricted),'Collateral-only; '+M(w.unvestedRestricted)+' vesting')}${metric('Locked position value',M(metrics.locked)+' CCLX','Gross reserve units, before exit fees')}</div>`+
`<div class="grid g2" style="margin-top:18px">${card('Trade / convert',`<div class="subtabs">${[['buy','Buy'],['sell','Sell'],['convert','Legacy conversion']].map(([k,t])=>`<button class="subtab ${state.mockSide===k?'active':''}" data-mock-side="${k}">${t}</button>`).join('')}</div><div class="form-grid"><div class="field field-wide"><label>${state.mockSide==='convert'?'CO2BIT to convert':state.mockSide==='buy'?'USD to spend':'CCLX to sell'}</label><input id="mock-amount" type="number" min="0" step="any" value="${state.mockAmount}"></div></div><div class="quote-box">${quote}</div>${btn(state.mockSide==='convert'?'Convert to restricted CCLX':state.mockSide==='buy'?'Preview and buy':'Preview and sell','mock-trade','primary full')}<p class="source-note">Execution is simulated against the current mock market, with a configurable slippage guard. Unfilled amounts remain in the wallet.</p>`,'No real tokens or funds are transferred.')}${card('Wallet & legacy rights',`<div class="wallet-stat"><span>Unrestricted liquid</span><strong>${M(w.liquid)} CCLX</strong></div><div class="wallet-stat"><span>Restricted, allocation-eligible</span><strong>${M(w.restricted)} CCLX</strong></div><div class="wallet-stat"><span>Restricted, vesting</span><strong>${M(w.unvestedRestricted)}</strong></div><div class="wallet-stat"><span>Restricted reward balance</span><strong>${M(w.restrictedRewards)}</strong></div><div class="wallet-stat"><span>Legacy CO2BIT entitlement</span><strong>${M(w.legacy)}</strong></div><div class="wallet-stat"><span>Simulation day</span><strong>${state.mock.day}</strong></div><div class="divider"></div>${kv([['Bridge reference value',U(b.value)],['Remaining global capacity',M(Math.max(0,b.available-state.mock.bridgeClaimed))+' CCLX'],['Current owner allowance','Subject to vesting and caps']])}<div class="page-actions">${btn('Advance 30 days','advance-30')}${btn('Advance 365 days','advance-365')}</div><p class="source-note">The conversion ratio and 3.3M reference value are illustrative. A real bridge requires an eligibility snapshot, binding terms and a verified identity register.</p>`)}</div>`+
`<div class="section-label">Available projects <span class="subtle">Different economic and curve parameters</span></div><div class="grid g3">${metrics.pools.map(p=>`<div class="card project-card"><div class="project-visual ${p.id}"><span class="project-monogram">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span>${badge(p.type,p.type==='Green Debt'?'blue':'green')}</div><div class="project-name">${esc(p.name)}</div><div class="project-meta">${esc(p.sector)} · ${esc(p.location)}</div><div class="project-apr">${P(p.totalAPR)}</div><div class="metric-note">Indicative total APR · not guaranteed</div><div class="divider"></div>${kv([['Real yield',P(p.realAPR)],['Bootstrap rewards',P(p.bootstrapAPR)],['Collateral',M(p.locked)+' CCLX'],['Capacity',M(p.capacity)+' CCLX'],['Risk PD / LGD',P(p.defaultPD)+' / '+P(p.lgd)]])}<div class="project-footer">${badge('Stage '+p.stage,'blue')}${btn('Explore pool','choose-project:'+p.id,'primary')}</div></div>`).join('')}</div>`+
`<div class="section-label">Project pool / ${esc(p.name)}</div><div class="grid g2">${card('Allocate collateral',`<div class="form-grid">${select('Source balance','allocation-source',[['liquid','Unrestricted CCLX'],['restricted','Restricted CCLX'],['restrictedRewards','Restricted rewards']],state.mockRestricted?'restricted':'liquid')}<div class="field"><label>Amount in CCLX</label><input id="pool-amount" type="number" min="0" step="any" value="${state.mockAmount}"></div></div><div class="quote-box">${kv([['Curve spot (receipt unit)',F(curveSpot(v.a,v.b,v.shares),5)],['Backing reserve',M(v.backing)+' CCLX'],['Curve fee',P(v.fee)],['Remaining capacity',M(v.capacity-v.backing)+' CCLX']])}</div><div class="actions">${btn('Deposit collateral','mock-allocate','primary')}${btn('Withdraw from position','mock-withdraw')}</div><p class="source-note">A deposit mints an internal project receipt. It is not a tradable project token or an ownership claim. Restricted receipts retain their provenance on withdrawal.</p>`,'Select a source, then deposit or withdraw.')}${card('Project-specific bonding curve',`<div class="chart-title">Marginal receipt price versus receipt supply — synthetic</div>${chart([{name:'Curve price',values:Array.from({length:41},(_,i)=>curveSpot(v.a,v.b,v.shares*(.2+i*.04))),color:colours.green}],{labels:Array.from({length:41},(_,i)=>M(v.shares*(.2+i*.04))),format:x=>F(x,3)})}<div class="chart-caption">The curve is reserve-backed. A milestone can authorize a parameter review, but never creates an unfunded price floor. The underlying financing contract and its investors are separate.</div><div class="page-actions">${btn('Verify next mock milestone','mock-verify')}</div>` )}</div>`+
`<div class="section-label">Rewards and positions</div><div class="grid g2">${card('Claimable rewards',kv([['Real cash yield',U(metrics.pendingReal,2)],['Unrestricted bootstrap',M(positions.reduce((s,p)=>s+p.rewardLiquid,0))+' CCLX'],['Restricted bootstrap',M(positions.reduce((s,p)=>s+p.rewardRestricted,0))+' CCLX'],['Cumulative rewards emitted',M(state.mock.rewardSpent)+' CCLX']])+`<div class="page-actions">${btn('Claim accrued rewards','mock-claim','primary')}</div><p class="source-note">Real yield is paid from synthetic distributable fees. Bootstrap rewards draw from the fixed emissions budget. The demo uses collateral-weighted accrual; production requires time-weighted balances and independently verified cash settlements.</p>`)}${card('Protocol event ledger',state.mock.log.length?`<div class="feed">${state.mock.log.slice(0,8).map(l=>`<div class="feed-row"><div class="feed-icon">↗</div><div><div class="feed-title">${esc(l.type)}</div><div class="feed-meta">Day ${l.day} · ${esc(l.detail)}</div></div></div>`).join('')}</div>`:'<div class="empty">No mock transactions yet.</div>')}</div>`+
card('Open positions',table(['Project','Provenance','Receipt shares','Redemption value','Real yield','Bootstrap','Debt'],positions.map(x=>[esc(config.projects.find(p=>p.id===x.projectId)?.name),badge(x.restricted?'Restricted':'Unrestricted',x.restricted?'purple':'green'),M(x.shares),M(x.value)+' CCLX',U(x.realUSD,2),M(x.rewardLiquid+x.rewardRestricted),U(x.debtUSD)])),'Receipts are internal accounting units; only the unrestricted principal path can become freely transferable.')+
`<div class="section-label">Financing rights remain separate</div><div class="grid g2">${card('Carbon Forward / Climate Credit','Capital is committed under an offtake or forward contract. Future verified environmental assets are delivered under that contract. CCLX collateral does not automatically convey those assets.','Contractual funding branch')}${card('Green Bond / Green Debt','Debt investors receive contractual principal and interest, plus Reporting and Transparency. They do not automatically receive carbon credits or ownership rights.','Hybrid arrangements require separate documented rights.')}</div>`;}

function curveLab(){
 const cfg=state.curveConfig,errors=validateCurveConfig(cfg),projects=materializeCurveProjects(cfg);if(!projects.find(p=>p.id===state.curveProjectId))state.curveProjectId=projects[0]?.id;
 const p=projects.find(x=>x.id===state.curveProjectId)||projects[0],idx=cfg.projects.findIndex(x=>x.id===p?.id),vault=p?makeVault(p):null,series=vault?curveSeries(vault.curve,Math.max(vault.shares*1.8,1),54):[],r=state.curveResult,opt=state.curveOptimizer,s=r?.summary;
 const tabs=curveTabs(),actions=btn('Run simulation','run-curve','primary')+btn('Run optimizer','run-curve-optimizer')+btn('Use condensed v5 preset','curve-preset-condensed');
 const header=title('Bonding Curve Lab','Simulate project-specific collateral vault curves, participant activity, migrations and fee collection. Project financing remains a documented experimental mode until NAV, haircuts, queues and defaults are fully modeled.','01 / PRODUCT / BONDING CURVES',actions)+notice('All hypotheses are synthetic unless explicitly marked otherwise. The baseline model uses reserve-backed receipts; it does not turn receipts into project-financing rights. CCLX fees are quantities first and only indicative USD value until an explicit sale is simulated.','blue')+(errors.length?notice(errors.map(esc).join('<br>'),'red'):'');
 const overview=()=>`${tabs}<div class="grid g4">${metric('Fees collected',s?M(s.cumulativeFeesCCLX)+' CCLX':'Not run','Curve fees only; external annualProtocolFees separate')}${metric('Net result',s?U(s.netProtocolResultUSD,2):'Not run','Indicative fee value minus modeled costs')}${metric('Active projects',F((r?.daily.at(-1)?.phaseCounts.open_for_deposits||0)+(r?.daily.at(-1)?.phaseCounts.operating||0)||projects.filter(x=>phaseForProject(x,0)!=='not_created').length),'States tracked separately')}${metric('Rejected demand',s?P(s.rejectedDemandRate,2):'Not run','Capacity, holdings, slippage and phase refusals')}</div><div class="grid g2" style="margin-top:18px">${card('Economic mode',kv([['Current mode',cfg.mode],['Project financing controls',cfg.projectFinancing.enabled?'Enabled':'Disabled'],['Price source',cfg.priceSource.mode+' · '+U(cfg.priceSource.cclxUsd,3)],['Network mode',cfg.networkMode],['Scenario seed',cfg.seed]])+`<p class="source-note">${esc(cfg.projectFinancing.reason)} The app keeps cash available, deployed capital, NAV and losses out of the baseline until that mode is explicitly implemented.</p>`)}${card('Document/code gap register',checksView([{name:'Baseline receipts',detail:'Existing code models reserve-backed collateral vault receipts, not legal financing rights.',pass:true},{name:'condensed_v5 floors',detail:'USD floor buffers are converted using an explicit CCLX/USD reference and exported with source metadata.',pass:true},{name:'Milestone steps',detail:'Piecewise/milestone curves are available as synthetic curves; they are not claimed to reproduce the PDF exactly.',pass:true},{name:'External fees',detail:'annualProtocolFees remain external_only unless a non-overlapping consolidation mapping is chosen.',status:'unverified'}]))}</div>${r?`<div class="section-label">Latest run</div><div class="grid g3">${metric('Action frequency',F(s.actionFrequencyMonthly,3),'decisions/active participant/month')}${metric('Vault turnover',F(s.vaultTurnover,3),'Deposits + withdrawals + both migration legs / average reserve')}${metric('Migration rate',F(s.migrationRate,3),'Network migration capital counted once')}</div>`:''}`;
 const designer=()=>{let qd='',qw='';try{qd=kv([['Gross deposit',M(state.curveQuoteAmount)+' CCLX'],['Minted receipts',M(quoteDeposit(vault,state.curveQuoteAmount,{mintFee:p.fees.mintFee,allowPartial:true}).shares)],['Entry fee',M(quoteDeposit(vault,state.curveQuoteAmount,{mintFee:p.fees.mintFee,allowPartial:true}).fee)+' CCLX'],['Average slippage',P(quoteDeposit(vault,state.curveQuoteAmount,{mintFee:p.fees.mintFee,allowPartial:true}).averageSlippage,3)]]);qw=kv([['Shares burned',M(Math.min(state.curveWithdrawalShares,vault.shares*.25))],['Net output',M(quoteWithdrawal(vault,Math.min(state.curveWithdrawalShares,vault.shares*.25),{redemptionFee:p.fees.redemptionFee}).output)+' CCLX'],['Exit fee',M(quoteWithdrawal(vault,Math.min(state.curveWithdrawalShares,vault.shares*.25),{redemptionFee:p.fees.redemptionFee}).fee)+' CCLX'],['Average exit impact',P(quoteWithdrawal(vault,Math.min(state.curveWithdrawalShares,vault.shares*.25),{redemptionFee:p.fees.redemptionFee}).averageSlippage,3)]]);}catch(e){qd=notice(esc(e.message),'red');qw='';}
 return `${tabs}<div class="grid g2">${card('Project and curve parameters',`${curveSelect('Project','curveProject',projects.map(p=>[p.id,p.name]),p.id)}${idx>=0?`<div class="form-grid" style="margin-top:14px">${curveSelect('Curve family',`projects.${idx}.curve.family`,[['linear','Linear'],['power','Power'],['piecewise','Piecewise'],['milestone_steps','Milestone steps']],cfg.projects[idx].curve.family)}${curveInput('Capacity CCLX',`projects.${idx}.capacityCCLX`,cfg.projects[idx].capacityCCLX,100000)}${curveInput('Initial reserve / floor CCLX',`projects.${idx}.floorBuffer.value`,cfg.projects[idx].floorBuffer.value,100000)}${curveInput('Linear a / initial price',`projects.${idx}.curve.a`,cfg.projects[idx].curve.a??cfg.projects[idx].curve.initialPrice,.01,'CCLX per receipt')}${curveInput('Linear b / slope',`projects.${idx}.curve.b`,cfg.projects[idx].curve.b??0,1e-8)}${curveInput('Economic initial price',`projects.${idx}.curve.initialPrice`,cfg.projects[idx].curve.initialPrice??1,.01)}${curveInput('Price at capacity/ref',`projects.${idx}.curve.priceAtCapacity`,cfg.projects[idx].curve.priceAtCapacity??1.6,.01)}${curveInput('Convexity n',`projects.${idx}.curve.convexity`,cfg.projects[idx].curve.convexity??1.35,.05)}${curveInput('Mint fee',`projects.${idx}.fees.mintFee`,cfg.projects[idx].fees.mintFee,.001)}${curveInput('Redemption fee',`projects.${idx}.fees.redemptionFee`,cfg.projects[idx].fees.redemptionFee,.001)}</div>`:'<p class="source-note">Generated schedule projects inherit template parameters. Edit the template project to change future cohorts.</p>'}<p class="source-note">Capacity is a CCLX reserve cap. Family coefficients are technical curve parameters calculated or stored from the selected economic convention; changing family does not create backing.</p>`)}${card('Curve chart and live quote',`<div class="chart-title">P(S) marginal price and R(S) reserve integral</div>${chart([{name:'P(S)',values:series.map(x=>x.spot),color:colours.green},{name:'R(S) / 1M',values:series.map(x=>x.reserve/1e6),color:colours.blue}],{labels:series.map(x=>M(x.supply)),format:x=>F(x,3)})}<div class="form-grid">${curveInput('Deposit quote amount',`ui.curveQuoteAmount`,state.curveQuoteAmount,1000)}${curveInput('Withdrawal quote shares',`ui.curveWithdrawalShares`,state.curveWithdrawalShares,1000)}</div><div class="quote-box">${qd}</div><div class="quote-box">${qw}</div><p class="source-note">Deposit slippage, marginal price movement and user fees are separate metrics. Withdrawal output is calculated by burning receipts on the curve, not by a proportional reserve shortcut.</p>`)}</div>`};
 const flows=()=>`${tabs}<div class="grid g2">${card('Population and capital',`<div class="form-grid">${curveInput('Initial participants','participants.initial',cfg.participants.initial,100)}${curveInput('New entrants / day','participants.newPerDay',cfg.participants.newPerDay,1)}${curveInput('Budget per new entrant','participants.budgetPerNewParticipantCCLX',cfg.participants.budgetPerNewParticipantCCLX,100)}${curveInput('Initial wallet capital','totalInitialCapitalCCLX',cfg.totalInitialCapitalCCLX,100000)}${curveInput('Median ticket','capital.medianTicketCCLX',cfg.capital.medianTicketCCLX,100)}${curveInput('Ticket dispersion','capital.dispersion',cfg.capital.dispersion,.05)}${curveInput('Whale share','capital.whaleShare',cfg.capital.whaleShare,.01)}${curveInput('Wealth concentration','capital.whaleWealthShare',cfg.capital.whaleWealthShare,.01)}</div>`)}${card('Activity and demand',`<div class="form-grid">${curveInput('Active share','participants.activeShare',cfg.participants.activeShare,.01)}${curveInput('Actions / active month','activity.actionsPerActiveMonth',cfg.activity.actionsPerActiveMonth,.1)}${curveInput('Movable fraction','activity.movableFraction',cfg.activity.movableFraction,.01)}${curveInput('Fee elasticity','activity.feeElasticity',cfg.activity.feeElasticity,.1)}${curveInput('Deposit probability','activity.depositProbability',cfg.activity.depositProbability,.01)}${curveInput('Withdraw probability','activity.withdrawProbability',cfg.activity.withdrawProbability,.01)}${curveInput('Migration probability','activity.migrationProbability',cfg.activity.migrationProbability,.01)}${curveInput('Max slippage','activity.maxSlippage',cfg.activity.maxSlippage,.01)}</div><p class="source-note">Flux imposés and behavioral demand are distinct. Behavioral mode includes a do-nothing choice and only uses prior state.</p>`)}</div><div class="section-label">Network growth schedule</div>${card('Project counts by day',table(['Day','Target active projects'],cfg.projectSchedule.map(x=>[x.day,x.targetActiveProjects]))+`<p class="source-note">Changing project count does not automatically create capital, participants, fees or yield. Use fixed_total_resources to keep the resource envelope constant, or fixed_per_project_resources to fund growth explicitly.</p>`)}`;
 const fees=()=>{let mig='';try{const ps=projects.filter(x=>x.id!==p.id),to=ps[0]||p,stateObj={vaults:Object.fromEntries([p,to].map(x=>[x.id,makeVault(x)]))};mig=kv([['Origin gross redemption','10,000.00 CCLX'],['Destination project',to.name],['Total fees',M(quoteMigration(stateObj,{originProject:p.id,destinationProject:to.id,shares:quoteDeposit(makeVault(p),10000,{mintFee:p.fees.mintFee,allowPartial:true}).shares,redemptionFee:p.fees.redemptionFee,mintFee:to.fees.mintFee,routingFee:cfg.fees.routingFee}).totalFees)+' CCLX'],['External capital added','0 CCLX']]);}catch(e){mig=notice(esc(e.message),'red');}
 return `${tabs}<div class="grid g2">${card('Fee policy',`<div class="form-grid">${curveInput('Default mint fee','fees.defaultMintFee',cfg.fees.defaultMintFee,.001)}${curveInput('Default redemption fee','fees.defaultRedemptionFee',cfg.fees.defaultRedemptionFee,.001)}${curveInput('Routing fee','fees.routingFee',cfg.fees.routingFee,.001)}${curveInput('Subsidy / action CCLX','fees.subsidyPerActionCCLX',cfg.fees.subsidyPerActionCCLX,1)}${curveInput('Rewards allocation','fees.allocations.rewards',cfg.fees.allocations.rewards,.01)}${curveInput('Reserve allocation','fees.allocations.reserve',cfg.fees.allocations.reserve,.01)}${curveInput('LP allocation','fees.allocations.lp',cfg.fees.allocations.lp,.01)}${curveInput('Operations allocation','fees.allocations.operations',cfg.fees.allocations.operations,.01)}</div><p class="source-note">Allocations split already-collected fees. They are not new revenue and are checked to remain <= 100%.</p>`)}${card('Migration quote example',mig+`<p class="source-note">Baseline migration is atomic: if the destination deposit refuses capacity/slippage/provenance, neither leg executes and no fee is charged. A wallet-delayed route would be a separate mode.</p>`)}</div><div class="section-label">Fee accounts by project</div>${card('Latest fee ledger',r?table(['Project','Gross','Net','Entry','Exit','Routing','Restricted'],Object.entries(r.feeAccounts.byProject).map(([id,v])=>[id,M(v.gross),M(v.net),M(v.entry),M(v.exit),M(v.routing),M(v.restricted)])):'<div class="empty">Run a simulation to populate fee accounts.</div>')}`};
 const simulation=()=>`${tabs}<div class="grid g2">${card('Run controls',`${curveSelect('Scenario','curveScenario',CURVE_LAB_SCENARIOS.map(s=>[s.id,s.name]),state.curveScenario)}<div class="form-grid" style="margin-top:14px">${curveSelect('Network mode','networkMode',[['fixed_network','Fixed network'],['fixed_total_resources','Fixed total resources'],['fixed_per_project_resources','Fixed per-project resources'],['endogenous_growth','Endogenous growth']],cfg.networkMode)}${curveInput('Horizon days','horizonDays',cfg.horizonDays,30)}${curveInput('Seed','seed',cfg.seed,1)}${curveInput('Reserve budget CCLX','totalInitialReserveBudgetCCLX',cfg.totalInitialReserveBudgetCCLX,100000)}</div><div class="page-actions">${btn('Run selected scenario','run-curve','primary')}${btn('Reset lab defaults','curve-reset')}</div>`)}${card('Scenario library',table(['Scenario','Purpose'],CURVE_LAB_SCENARIOS.map(s=>[esc(s.name),esc(s.description)])))}</div>${r?`<div class="section-label">Daily series</div><div class="grid g2">${card('Reserves and fees',chart([{name:'Reserves CCLX',values:r.daily.map(x=>x.reservesCCLX),color:colours.green},{name:'Fees CCLX',values:r.daily.map(x=>x.feesCCLX),color:colours.blue}],{labels:r.daily.map(x=>x.day),format:M}))}${card('Volume decomposition',chart([{name:'Deposits',values:r.daily.map(x=>x.depositVolumeCCLX),color:colours.green},{name:'Withdrawals',values:r.daily.map(x=>x.withdrawalVolumeCCLX),color:colours.amber},{name:'Migrations',values:r.daily.map(x=>x.migrationVolumeCCLX),color:colours.purple}],{labels:r.daily.map(x=>x.day),format:M}))}</div><div class="section-label">Project states by date</div>${card('State counts',table(['Day','Announced','Open','Funded','Operating','Matured/closed','Rejected','Residual'],r.daily.filter((_,i)=>i%Math.max(1,Math.round(r.daily.length/12))===0||i===r.daily.length-1).map(x=>[x.day,x.phaseCounts.announced,x.phaseCounts.open_for_deposits,x.phaseCounts.funded,x.phaseCounts.operating,x.phaseCounts.matured+x.phaseCounts.closed,x.rejected,F(x.accountingResidualCCLX,6)])))}`:'<div class="empty"><h3>No curve simulation yet.</h3><p>Choose a scenario and run the worker to generate daily reserves, transactions, fees and accounting checks.</p></div>'}`;
 const optimizer=()=>`${tabs}<div class="grid g2">${card('Search setup',table(['Parameter','Range'],Object.entries(DEFAULT_SEARCH_SPACE).map(([k,v])=>[k,v.values?v.values.join(', '):`${v.min} → ${v.max}`]))+`<div class="page-actions">${btn('Run bounded search','run-curve-optimizer','primary')}${btn('Export candidates CSV','export-curve-candidates')}</div><p class="source-note">The search compares candidates under fixed assumptions and reports “best among candidates tested”, never a guaranteed real optimum.</p>`)}${card('Constraints',checksView(DEFAULT_CONSTRAINTS.map(c=>({name:c,detail:'Editable demonstration constraint from the spec.',pass:!opt||true}))))}</div>${opt?`<div class="section-label">Candidate results</div><div class="grid g4">${metric('Tested',F(opt.summary.tested),'candidate configs')}${metric('Feasible',F(opt.summary.feasible),'after accounting/slippage/refusal checks')}${metric('Pareto',F(opt.summary.pareto),'non-dominated feasible')}${metric('Best net result',opt.best?U(opt.best.netProtocolResult,2):'None','under selection seeds')}</div>${card('Optimization candidates',table(['ID','Mint fee','Exit fee','Slope','Projects','Net result','Retention','P95 cost','Rejected','Feasible','Pareto','Violations'],opt.candidates.slice(0,30).map(c=>[c.candidateId,P(c.mintFee,2),P(c.redemptionFee,2),F(c.slopeScale,2),`${c.initialProjects}→${c.targetProjects}`,Number.isFinite(c.netProtocolResult)?U(c.netProtocolResult,0):'Invalid',P(c.retention90d,1),P(c.p95RoundTripCost,2),P(c.rejectedDemandRate,1),badge(c.feasible?'Yes':'No',c.feasible?'green':'red'),c.paretoRank,c.violations.join('; ')])))}`:'<div class="empty"><h3>No optimizer run yet.</h3><p>Run the bounded search to compare fee, slope, cooldown and network-growth candidates.</p></div>'}`;
 const ledger=()=>`${tabs}<div class="grid g2">${card('Exports',`<div class="page-actions">${btn('Export config JSON','export-curve-config','primary')}${btn('Export results JSON','export-curve-result')}${btn('Export network CSV','export-curve-network')}${btn('Export transactions CSV','export-curve-transactions')}${btn('Export report MD','export-curve-report')}</div><p class="source-note">The same result object powers the UI and exports: seed, version, price source, assumptions, series, transactions and warnings.</p>`)}${card('Assumption register',table(['Path','Unit','Origin','Domain'],PARAMETER_REGISTER.map(x=>[x.path,x.unit,x.origin,x.domain])))}</div>${r?`<div class="section-label">Transaction trace</div>${card('Latest transactions',table(['Event','Day','Participant','Action','From','To','Requested','Executed','Fees','Status','Reason'],r.transactions.slice(-80).reverse().map(t=>[t.eventId,t.day,t.participantId,t.action,t.originProject,t.destinationProject,F(t.requestedAmount,2)+' '+t.unit,F(t.executedAmount,2),F(t.feesCCLX,4),badge(t.status,t.status==='executed'?'green':t.status==='partial'?'amber':'red'),esc(t.rejectionReason)])))}`:'<div class="empty">Run a simulation to inspect transactions and reconciled accounts.</div>'}`;
 const bodies={overview,designer,flows,fees,simulation,optimizer,ledger};
 return header+(bodies[state.curveTab]||overview)();
}

function liquidity(){const a=initialLiquidityAudit(config),m=makeMarket(config),sell=executeSell(m,state.quoteAmount),buy=executeBuy(m,state.quoteAmount*config.launchPrice),q=state.quoteSide==='sell'?sell:buy,size=sizeLiquidity(config),frontier=liquidityFrontier(config),grid=priceDepthGrid(config);return title('Initial liquidity & market depth','Verify the actual funding requirement, executable bid/ask depth, AMM reserves and price impact. Market-maker inventory is not cash and treasury funds are not automatically exchange liquidity.','02 / ECONOMIC LAB',btn('Run audit','refresh','primary'))+
notice('This is a synthetic launch book. The 1.5M USD quote allocation and 8M token inventory are separate resources. Displayed order-book depth is not independently verified, and real MM quotes can disappear.','blue')+
`<div class="grid g4">${metric('Authorized quote budget',U(a.budget),U(a.unallocatedCash)+' unallocated')}${metric('CEX quote / DEX quote',U(config.liquidity.cexQuote)+' / '+U(config.liquidity.dexQuote),'Not token inventory value')}${metric('MM inventory',M(a.inventory)+' CCLX',U(a.inventoryValue)+' reference value')}${metric('2% executable bid depth',U(a.within2),a.checks.find(x=>x.name.includes('depth target'))?.pass?'Working target met':'Working target not met',a.checks.find(x=>x.name.includes('depth target'))?.pass?'':'bad')}</div>`+
`<div class="grid g2" style="margin-top:18px">${card('Launch configuration',`<div class="form-grid">${input('Quote budget USD','liquidity.budget',config.liquidity.budget,100000)}${input('CEX bid cash USD','liquidity.cexQuote',config.liquidity.cexQuote,50000)}${input('DEX quote reserve USD','liquidity.dexQuote',config.liquidity.dexQuote,50000)}${input('DEX token reserve','liquidity.dexTokens',config.liquidity.dexTokens,10000)}${input('CEX token inventory','liquidity.cexTokens',config.liquidity.cexTokens,10000)}${input('2% depth target USD','liquidity.depthTarget',config.liquidity.depthTarget,50000)}${input('Reference trade tokens','liquidity.tradeTarget',config.liquidity.tradeTarget,10000)}${input('Max reference slippage','liquidity.slippageTarget',config.liquidity.slippageTarget,.001,'Fraction: 0.01 = 1%')}</div><p class="source-note">Changing reserves does not magically preserve the starting spot: use a quote/token ratio consistent with the reference price. Edit the full cumulative CEX ladder in Assumptions.</p>`)}${card('Funding and launch checks',checksView(a.checks)+`<div class="divider"></div>${size.feasible?kv([['Indicative required quote budget',U(size.requiredBudget)],['CEX quote allocation',U(size.requiredCexQuote)],['DEX quote allocation',U(size.requiredDexQuote)],['Required token inventory',M(size.requiredTokens)+' CCLX']]):notice(esc(size.reason),'red')}<p class="source-note">The sizing solver scales the supplied book shape. It does not prove that exchange liquidity or MM inventory can be sourced at these costs.</p>`)}</div>`+
`<div class="section-label">Executable depth / marginal-price bands</div><div class="grid g2">${card('Bid and ask depth ladder',table(['Distance','Bid cash','DEX quote','Total bids','Ask notional'],a.bands.map(r=>['±'+r.bps+' bps',U(r.cex),U(r.dex),U(r.total),U(marketDepth(m,r.bps,'buy').total)])),'Fees are reported in execution quotes; depth is not the average slippage of a trade.')}${card('Reference execution simulator',`<div class="form-grid">${select('Side','quote-side',[['sell','Sell CCLX'],['buy','Buy CCLX']],state.quoteSide)}<div class="field"><label>Order size (CCLX)</label><input id="quote-amount" type="number" min="0" step="1000" value="${state.quoteAmount}"></div></div><div class="quote-box">${kv(state.quoteSide==='sell'?[['Input',M(state.quoteAmount)+' CCLX'],['Net proceeds',U(q.quote,2)],['Average price',U(q.average,5)],['Slippage',P(q.slippage,3)],['Unfilled',M(q.unfilled)+' CCLX']]:[['Quote offered',U(state.quoteAmount*config.launchPrice)],['Tokens acquired',M(q.tokens)],['Average price',U(q.average,5)],['Slippage',P(q.slippage,3)],['Unspent cash',U(q.unfilled)]])}</div><div class="chart-title">Maximum executable size at a given slippage</div>${table(['Slippage limit','Sell tokens','Sell notional','Buy cash'],a.capacity.map(r=>[P(r.slippage),M(r.sell.input),U(r.sell.notional),U(r.buy.input)]))}<p class="source-note">These figures assume the initial book has not been consumed by earlier orders. The stress engine maintains finite reserves across months.</p>`)}</div>`+
`<div class="section-label">Liquidity sizing frontier</div>${card('Capital versus executable depth',chart([{name:'2% bid depth',values:frontier.map(x=>x.depth2),color:colours.green},{name:'Quote capital',values:frontier.map(x=>x.budget),color:colours.blue}],{labels:frontier.map(x=>x.scale+'×'),format:U})+table(['Scale','Quote budget','Token inventory','Depth ±2%','Sell slippage','Inventory within allocation'],frontier.map(x=>[x.scale+'×',U(x.budget),M(x.tokenInventory),U(x.depth2),P(x.sellSlippage,2),badge(x.inventoryOK?'Yes':'No',x.inventoryOK?'green':'red')])),'Scaling a synthetic book is a capital-sizing exercise, not evidence of a real market-making commitment.')}`+
`<div class="section-label">Price × size market-depth heatmap</div>${card('Sell-side impact by reference price',table(['Price / order',...grid[0].trades.map(x=>M(x.tokens)+' CCLX')],grid.map(row=>[U(row.price,4),...row.trades.map(t=>{const z=t.slippage;return `<span class="heat-cell ${z>.1?'critical':z>.03?'watch':'normal'}">${P(z,1)}</span>`;})])),'Each cell resets the same initial synthetic book at a different reference price; it does not assume the DEX automatically receives new capital when price changes.')}`;}

function funding(){
 const f=fundingTable(config),schedule=unlockSchedule(config,state.months),u=unlockPressureAudit(config,state.months),b=bridgeQuote(config),bs=buckets(config);
 const raised=sum(f.map(x=>x.raised)),tokens=sum(f.map(x=>x.tokens));
 const fundingRows=f.map(x=>[esc(x.name),U(x.price,3),U(x.fdv),M(x.tokens),P(x.share),U(x.raised),x.cliff+'m',x.linear+'m',P(x.tge)]);
 fundingRows.push(['TOTAL','—','—',M(tokens),P(tokens/config.supply),U(raised),'—','—','—']);
 const fundingCard=card('Round pricing and valuation',table(['Round','Price','FDV','Tokens','Supply','Proceeds','Cliff','Linear','TGE'],fundingRows),'FDV = round price × maximum supply. This is a token-sale funding table, not the equity cap table of CCL. Prices and terms are working proposals, not confirmed transactions.');
 const allocBody=config.allocations.map(a=>`<div class="progress-row"><span>${esc(a.name)}</span><strong>${M(a.tokens)} · ${P(a.tokens/config.supply)}</strong></div>${progress(a.tokens,config.supply,a.id==='rewards'?'blue':'green')}`).join('')+'<p class="source-note">The 18% Team & Founders bucket includes an internal legacy conversion capacity. All material allocations and beneficial ownership terms must be transparently disclosed.</p>';
 const bridgeBody=kv([['Internal capacity',M(config.bridge.internalCap)+' CCLX'],['Reference valuation ceiling',U(config.bridge.valuationCap)],['Eligible legacy supply',M(config.bridge.eligibleSupply)+' CO2BIT'],['Illustrative ratio',F(b.ratio,2)+':1'],['Restricted release',config.bridge.cliff+'m cliff + '+config.bridge.linear+'m linear'],['Free market-sale entitlement','0 CCLX']])+'<p class="source-note">No new supply outside the 200M ceiling. The reference valuation is not evidence of CO2BIT market value. Actual entitlement, identity, burn/lock and claim rules require formal validation.</p>';
 const vestRows=bs.filter(x=>x.kind==='liquid'||x.kind==='restricted').map(b=>{
   const round=config.rounds.find(r=>r.id===b.id),path=round?'rounds.'+config.rounds.indexOf(round):null;
   const editable=(key,value,scale=1)=>path?`<input class="tbl-input" type="number" data-config="${path}.${key}" data-scale="${scale}" value="${value*scale}" min="0" step="any">`:F(value*scale,2);
   return [esc(b.name),M(b.tokens),editable('cliff',b.cliff),editable('linear',b.linear),editable('tge',b.tge,100),editable('sellRate',b.sellRate,100)];
 });
 const vestCard=card('Round and internal vesting table',table(['Bucket','Tokens','Cliff m','Linear m','TGE %','Sale rate %'],vestRows)+'<p class="source-note">Cliff + linear duration is measured from TGE. Non-sale buckets use governed or programmatic schedules. Their circulating status does not automatically imply unrestricted market sales.</p>','Editable sale rounds. All other parameters are available in Assumptions.');
 const cumulativeChart=chart([{name:'Ordinary vested',values:schedule.map(r=>r.liquid),color:colours.green},{name:'Restricted eligible',values:schedule.map(r=>r.restricted),color:colours.purple},{name:'Reward ceiling',values:schedule.map(r=>r.rewardCeiling),color:colours.blue}],{labels:schedule.map(r=>'M'+r.month),format:M});
 const pressureChart=chart([{name:'Expected unlock sales',values:u.map(r=>r.pressure),color:colours.amber},{name:'Initial 2% depth',values:u.map(r=>r.depth),color:colours.blue}],{labels:u.map(r=>'M'+r.month),format:U});
 const painRows=u.map(r=>{const status=r.coverage===null?'No sales':r.coverage<1?'Critical':r.coverage<config.liquidity.coverageTarget?'Watch':'Covered';return ['M'+r.month,M(r.unlocked),M(r.restricted),M(r.expectedSell),U(r.pressure),U(r.depth),r.coverage===null?'—':F(r.coverage,2)+'×',U(r.gap),badge(status,status==='Critical'?'red':status==='Watch'?'amber':'green')];});
 const painCard=card('Unlock pain-zone table',table(['Month','Ordinary unlocked','Restricted release','Expected sell tokens','Sell notional','Initial depth','Coverage','Depth gap','Status'],painRows),'Coverage = initial 2% bid depth / assumed new unlock sell notional. A gap is the cash depth needed to meet the target; it is not automatically funded by the treasury.');
 const rewardCard=card('Capped reward budget — 26M over eight years',table(['Year','Budget CCLX','Cumulative','Share of max supply'],config.rewardBudget.map((v,i)=>['Y'+(i+1),M(v),M(sum(config.rewardBudget.slice(0,i+1))),P(v/config.supply)]))+'<p class="source-note">Emissions are a ceiling, not guaranteed APR. Actual distributions depend on eligible collateral, quality weights and the available budget. They are separate from realized cash yield.</p>');
 return title('Funding, vesting & unlocks','Reconcile the supply, funding rounds and release schedules, then map likely sale pressure against executable market depth. Restricted legacy releases are never counted as sellable supply.','02 / ECONOMIC LAB',btn('Export unlock CSV','export-unlocks'))+
 `<div class="grid g4">${metric('Maximum supply',M(config.supply),'Allocation sum '+M(sum(config.allocations.map(a=>a.tokens))))}${metric('Token-sale proceeds',U(raised),'Illustrative, before fees')}${metric('Token-sale allocation',M(tokens),P(tokens/config.supply)+' of maximum supply')}${metric('Reference initial float',M(initialFloat(config)),P(initialFloat(config)/config.supply)+' including MM inventory')}</div>`+
 '<div class="section-label">Funding / token sale cap table</div>'+fundingCard+
 '<div class="grid g2" style="margin-top:18px">'+card('Supply allocation',allocBody)+card('Restricted conversion capacity',bridgeBody)+'</div>'+
 '<div class="section-label">Editable vesting assumptions</div>'+vestCard+
 '<div class="section-label">Unlock calendar & pain-zone screening</div><div class="grid g2">'+
 card('Cumulative release',cumulativeChart+'<p class="chart-caption">Restricted principal is only allocation-eligible. Reward ceilings are not automatically issued or sellable. Governed treasury and MM inventory are not included in ordinary holder unlocks.</p>','','span2')+
 card('Static unlock pressure vs initial 2% depth',pressureChart+'<p class="chart-caption">This first-pass screen deliberately holds market depth and price constant. The Monte Carlo page tests how both deteriorate under stress.</p>','','span2')+'</div>'+painCard+
 '<div class="section-label">Bootstrap emission schedule</div>'+rewardCard;
}

function stress(){const r=state.stress,s=config.stress;return title('Monte Carlo & economic resilience','A monthly, seeded stochastic simulation with finite trading liquidity, correlated project revenue, defaults, vesting and capped rewards. Run the baseline or combine shocks.','02 / ECONOMIC LAB',btn('Run simulation','run-stress','primary')+btn('Run all scenarios','run-all'))+
notice('P05 / P50 / P95 are percentiles of synthetic simulated paths, not forecast confidence intervals. The external reference price is a stochastic assumption, not a model-derived fair value. Endogenous flow impact and arbitrage are simplified; no live market calibration is implied.','blue')+
`<div class="grid g2">${card('Scenario & simulation controls',`<div class="form-grid">${select('Scenario preset','stress-scenario',SCENARIOS.map(x=>[x.id,x.name]),state.scenario)}<div class="field"><label>Random seed</label><input data-config="stress.seed" type="number" step="1" value="${s.seed}"></div>${input('Paths','stress.paths',s.paths,1,'Recommended 100–300; all-scenario runs use at most 100 paths each',1)}${input('Horizon (months)','stress.months',s.months,1,'Up to 120 months',1)}${input('Annual drift','stress.annualDrift',s.annualDrift,.01,'0.05 = +5%; lognormal price process',-5)}${input('Annual volatility','stress.annualVol',s.annualVol,.05,'0.85 = 85% volatility')}${input('Jump probability / month','stress.jumpProbability',s.jumpProbability,.01)}${input('Jump mean log return','stress.jumpMean',s.jumpMean,.05,'Negative jumps allowed',-5)}${input('Shock month','stress.shockMonth',s.shockMonth,1)}${input('One-off shock','stress.shockSize',s.shockSize,.05,'-0.40 = -40%',-1)}</div><div class="page-actions">${btn('Run selected scenario','run-stress','primary')}${btn('Reset stress inputs','reset-stress')}</div>`,'Every parameter can also be edited in the JSON configuration.')}${card('Economic and liquidity controls',`<div class="form-grid">${input('Unlock selling rate','stress.unlockSellRate',s.unlockSellRate,.05)}${input('Reward selling rate','stress.rewardSellRate',s.rewardSellRate,.05)}${input('Organic monthly selling','stress.organicSellRate',s.organicSellRate,.001)}${input('Organic monthly buying','stress.organicBuyRate',s.organicBuyRate,.001)}${input('MM shock withdrawal','stress.mmShock',s.mmShock,.05)}${input('Monthly MM replenishment','stress.mmReplenishment',s.mmReplenishment,.05)}${input('Dedicated liquidity reserve USD','stress.liquidityReserve',s.liquidityReserve,50000)}${input('Explicit monthly external topup','stress.liquidityTopup',s.liquidityTopup,10000)}${input('Finite arbitrage cash USD','stress.externalArbCash',s.externalArbCash,50000)}${input('Finite arbitrage tokens','stress.externalArbTokens',s.externalArbTokens,100000)}${input('Project default multiplier','stress.projectDefaultMultiplier',s.projectDefaultMultiplier,.25)}${input('Revenue growth','stress.revenueGrowth',s.revenueGrowth,.05,'Annualized',-5)}${input('Staking participation','stress.stakingParticipation',s.stakingParticipation,.05)}${input('Maximum execution slippage','stress.maxExecutionSlippage',s.maxExecutionSlippage,.05)}</div><p class="source-note">The liquidity reserve is not project collateral or a general risk reserve. External arbitrage accounts are finite and are not protocol cash. Market makers cannot replenish bids beyond cash actually allocated.</p>`)}</div>`+
`<div class="section-label">${r?'Latest simulation results':'Run a scenario to calculate the risk distribution'}</div>`+(r?stressResults(r):`<div class="grid g3">${SCENARIOS.filter(x=>x.id!=='base').map(x=>`<div class="scenario-card"><div class="scenario-title">${esc(x.name)}</div><div class="scenario-text">${esc(x.description)}</div>${btn('Select scenario','scenario:'+x.id,'small')}</div>`).join('')}</div>`);}
function stressResults(r){if(r.scenarios)return `<div class="grid g3">${r.scenarios.map(x=>card(esc(x.name),kv([['Median terminal price',U(x.summary.terminalPrice.p50,4)],['P05 terminal price',U(x.summary.terminalPrice.p05,4)],['Depth breach probability',P(x.summary.depthBreachProbability)],['Reserve shortfall probability',P(x.summary.reserveExhaustionProbability)],['Median max drawdown',P(x.summary.maxDrawdown.p50)]])+`<div class="page-actions">${btn('Select and rerun','scenario:'+x.id,'small')}</div>`)).join('')}</div>`;
const z=r.series,sm=r.summary;return `<div class="grid g4">${metric('Terminal price / median',U(sm.terminalPrice.p50,4),'P05 '+U(sm.terminalPrice.p05,4)+' · P95 '+U(sm.terminalPrice.p95,4))}${metric('Depth breach probability',P(sm.depthBreachProbability),'Any month below '+F(config.liquidity.coverageTarget,2)+'× coverage',sm.depthBreachProbability>.05?'bad':'good')}${metric('Liquidity reserve shortfall',P(sm.reserveExhaustionProbability),'Refill demand exceeds available reserve',sm.reserveExhaustionProbability>.05?'bad':'good')}${metric('Median maximum drawdown',P(sm.maxDrawdown.p50),'Across '+r.meta.paths+' paths')}</div>`+
`<div class="grid g2" style="margin-top:18px">${card('Price distribution',bandChart(z,'price',x=>U(x,3))+'<p class="chart-caption">Monthly reference price after simplified flow feedback. The individual executable book may have a different marginal price.</p>','P05 / median / P95','span2')}${card('Market depth and expected selling',chart([{name:'2% bid depth / median',values:z.map(x=>x.depth.p50),color:colours.blue},{name:'Total selling pressure / median',values:z.map(x=>x.totalPressureUSD.p50),color:colours.amber},{name:'Unlock selling / median',values:z.map(x=>x.unlockSalesUSD.p50),color:colours.red}],{labels:z.map(x=>'M'+x.month),format:U})+'<p class="chart-caption">Depth is measured before each month’s simulated flows. Total pressure includes queued selling, so repeated months may contain unexecuted orders from earlier periods.</p>','', 'span2')}${card('Coverage and queue',bandChart(z,'coverage',x=>F(x,2)+'×')+chart([{name:'Median unfilled queue (CCLX)',values:z.map(x=>x.queue.p50),color:colours.red}],{labels:z.map(x=>'M'+x.month),height:150,format:M})+'<p class="chart-caption">Coverage is capped at 10× for display; no-selling months are excluded from breach counts. Queued tokens are not counted as new unlocks in the next month.</p>','', 'span2')}</div>`+
`<div class="section-label">Unlock pain zones <span class="subtle">Probability of insufficient depth across paths</span></div>${card('Monthly stress heatmap',table(['Month','Median price','Median 2% depth','Unlock sales USD','Total pressure USD','Coverage P05 / P50','Breach probability','Unlock-only breach','Queued-sale probability','Zone'],z.map(x=>['M'+x.month,U(x.price.p50,4),U(x.depth.p50),U(x.unlockSalesUSD.p50),U(x.totalPressureUSD.p50),F(x.coverage.p05,2)+'× / '+F(x.coverage.p50,2)+'×',P(x.failProbability),P(x.unlockFailProbability),P(x.queueProbability),`<span class="heat-cell ${x.failProbability>=.5?'critical':x.failProbability>=.2?'watch':'normal'}">${x.zone}</span>`])),'Red = at least 50% of paths breach the coverage threshold; amber = at least 20%. Unlock-only breach isolates the new scheduled sell flow. The all-in measure includes rewards, organic flow and queued orders.')}`+
`<div class="grid g2" style="margin-top:18px">${card('Capital, emissions and project risk',kv([['Median minimum liquidity reserve',U(sm.liquidityReserve.p50)],['Median liquidity support consumed',U(sm.liquidityConsumed.p50)],['Median minimum risk reserve',U(sm.riskReserve.p50)],['Median realized cash yield',U(sm.realYield.p50)],['Median bootstrap emissions',M(sm.rewards.p50)+' CCLX'],['Median restricted rewards',M(sm.restrictedRewards.p50)+' CCLX'],['Median project defaults',F(sm.defaults.p50,1)],['Median uncovered project losses',U(sm.uncoveredLoss.p50)],['95% tail return / VaR',P(r.distribution.var95)],['Expected shortfall 95%',P(r.distribution.expectedShortfall95)]])+'<p class="source-note">VaR and expected shortfall are return-based scenario statistics. They can be negative under positive-return distributions and are not investment-loss guarantees.</p>')}${card('Simulation reproducibility',kv([['Paths',F(r.meta.paths)],['Horizon',r.meta.months+' months'],['Seed',r.meta.seed],['Engine','GBM + jumps + finite execution'],['Cohort release model','Cliff + linear vesting'],['Reward budget','Fixed annual emission ceilings'],['Restricted principal','Excluded from market sales'],['Data provenance','Synthetic / user-editable']])+`<div class="page-actions">${btn('Export full results JSON','export-stress','primary')}${btn('Export monthly CSV','export-stress-csv')}${btn('Export path summaries CSV','export-paths')}</div><p class="source-note">Sensitivity and scenario results should be recalibrated with independently verified market and cash-flow data before use in an investment decision.</p>`)}</div>`;}

function exploits(){const a=state.attacks,e=a?.economics||adversarialEconomics(config);return title('Exploit & adversarial economics','Exercise the actual mock ledger, curve and market functions. Separate passing model invariants from unverified smart-contract, oracle, identity and operational security.','02 / ECONOMIC LAB',btn('Run model attack suite','run-attacks','primary'))+
notice('This is a defensive test harness. It does not interact with deployed contracts, real exchanges or third-party systems. A passing JavaScript check does not establish EVM security or the absence of economic exploits.','blue')+
`<div class="grid g4">${metric('Model checks passed',a?F(a.passed):'—','Actual executable model functions')}${metric('Failed checks',a?F(a.failed):'—','Investigate before relying on results',a?.failed?'bad':'')}${metric('Unverified controls',a?F(a.unverified):'—','Require external evidence')}${metric('Restricted sale entitlement','0 CCLX','Principal and rewards collateral-only')}</div>`+
`<div class="section-label">Model-level attack suite</div>`+(a?card('Test results',a.results.map(x=>`<details class="attack-detail"><summary><span class="check-mark ${x.status==='pass'?'pass':x.status==='fail'?'fail':'unverified'}">${x.status==='pass'?'✓':x.status==='fail'?'×':'?'}</span><strong>${esc(x.name)}</strong><span class="badge ${x.severity==='Critical'?'red':'amber'}">${x.severity}</span><span class="badge ${x.status==='pass'?'green':x.status==='fail'?'red':'amber'}">${x.status}</span></summary><div class="expand-detail"><p><strong>Observed result:</strong> ${esc(x.detail)}</p><p><strong>Potential impact:</strong> ${esc(x.impact)}</p><p><strong>Mitigation / next control:</strong> ${esc(x.mitigation)}</p></div></details>`).join('')):card('Run the suite','<p class="card-sub">Checks cover restricted sales, withdrawals, reward provenance, conversion caps and replay, vesting, receipt transfers, borrowing, curve solvency, unfunded rebases, finite liquidity, emissions ceilings and double claims.</p>'+btn('Run checks','run-attacks','primary')))+
`<div class="section-label">Economic attack experiments</div><div class="grid g3">${card('Manipulation / sandwich proxy',kv([['Attacker spend',U(e.sandwich.attackerSpend)],['Victim spend',U(e.sandwich.victimSpend)],['Victim execution loss',M(e.sandwich.victimLossTokens)+' CCLX'],['Attacker round-trip P&L',U(e.sandwich.attackerPnL,2)]])+`<p class="source-note">${esc(e.sandwich.warning)}</p>`)}${card('Oracle / collateral distortion',kv([['Reference price',U(e.oracle.reference,4)],['Manipulated price',U(e.oracle.manipulated,4)],['Unsafe borrow capacity',U(e.oracle.unsafeBorrow)],['Guarded borrow capacity',U(e.oracle.guardedBorrow)]])+`<p class="source-note">Borrowing against restricted collateral is prohibited. Ordinary lending remains disabled by default, pending independent oracle controls.</p>`)}${card('Flash-staking capture',kv([['Illustrative epoch budget',M(e.flashStake.epochBudget)+' CCLX'],['Transient stake',M(e.flashStake.transientStake)],['Unsafe same-block capture',M(e.flashStake.unsafeCapture)],['Time-weighted guarded capture',M(e.flashStake.guardedCapture)]])+`<p class="source-note">${esc(e.flashStake.reason)} Production enforcement is unverified.</p>`)}</div>`+
`<div class="section-label">Required production security gates</div>${card('Unverified integration and operational controls',checksView([{category:'Identity',name:'Sybil / beneficial-owner aggregation',detail:'External KYC/UBO, sanctions and entitlement proofs are not connected.',status:'unverified'},{category:'Contracts',name:'Restricted transfer hooks and receipt wrappers',detail:'No Solidity implementation, EVM invariant fuzzing, reentrancy or independent audit.',status:'unverified'},{category:'Oracle',name:'Staleness, deviation and manipulation resistance',detail:'No signed external prices or on-chain TWAP implementation.',status:'unverified'},{category:'Execution',name:'MEV, flash loans and atomic claims',detail:'Time-weighted rewards and nonce checks are modeled, not deployed.',status:'unverified'},{category:'Operations',name:'MM mandates, reserve custody and emergency controls',detail:'No external evidence, custody reconciliation or incident response testing.',status:'unverified'}]))}`;}

function calibration(){const a=state.imported;return title('Market calibration','Import a user-supplied order-book snapshot to examine executable CEX depth. No live exchange connection is made and imported quotes are not assumed to belong to the protocol.','02 / ECONOMIC LAB',btn('Download CSV template','download-template'))+
notice('CSV columns: side,price,quantity,venue. Prices are USD per CCLX and quantity is in CCLX. A snapshot cannot establish persistence, spoofing resistance, actual MM ownership or execution latency. Do not treat unverified depth as committed launch capital.','blue')+
`<div class="grid g2">${card('Import a snapshot',`<div class="field"><label>Order-book CSV file</label><input id="orderbook-file" type="file" accept=".csv,text/csv"></div><div class="field" style="margin-top:15px"><label>Or paste CSV text</label><textarea id="orderbook-text" rows="9" placeholder="side,price,quantity,venue\nbid,0.2745,100000,Demo CEX\nask,0.2755,100000,Demo CEX"></textarea></div><div class="page-actions">${btn('Analyze pasted CSV','analyze-csv','primary')}${btn('Clear snapshot','clear-csv')}</div>`,'Imported evidence stays local in the browser.')}${card('Calibration checklist',checksView([{name:'Reference mid and spread',detail:'Use contemporaneous bid/ask quotes from the same market snapshot.',pass:true},{name:'Order-book depth',detail:'Import actual executable quantities and distinguish each venue.',pass:true},{name:'Liquidity provenance',detail:'Separate protocol-owned MM cash/inventory from third-party orders.',status:'unverified'},{name:'External arbitrage and replenishment',detail:'Supply finite limits and externally evidenced funding assumptions.',status:'unverified'},{name:'Historical calibration',detail:'Estimate volatility, jumps, flow elasticity, correlation and MM withdrawal behavior from relevant data.',status:'unverified'}]))}</div>`+
(a?`<div class="section-label">Imported snapshot analysis</div><div class="grid g4">${metric('Reference mid',U(a.mid,5),'From supplied best bid/ask')}${metric('Quoted spread',P(a.spread,3),'Snapshot only')}${metric('Bid quote',U(a.bidQuote),'Not committed protocol cash')}${metric('Quoted ask tokens',M(a.askTokens),'Snapshot only')}</div><div class="grid g2" style="margin-top:18px">${card('Imported executable depth',table(['Band','Bid quote','Ask quote'],a.depths.map(x=>['±'+x.bps+' bps',U(x.total),U(marketDepth({mid:a.mid,bids:a.bids,asks:a.asks,x:0,y:0,cexFee:config.liquidity.cexFee,dexFee:config.liquidity.dexFee},x.bps,'buy').total)])))}${card('Reference order execution',kv([['Sell input',M(config.liquidity.tradeTarget)+' CCLX'],['Sell proceeds',U(a.trade.quote)],['Sell slippage',P(a.trade.slippage,2)],['Unfilled sell',M(a.trade.unfilled)+' CCLX'],['Buy tokens received',M(a.buy.tokens)],['Buy slippage',P(a.buy.slippage,2)]])+`<p class="source-note">${esc(a.warning)}</p>`)}</div>`:'')+
`<div class="section-label">Model data requirements</div>${card('What to collect before calibration',table(['Dataset','Minimum useful fields','Purpose'],[['CEX L2 order books','Timestamp, venue, bid/ask prices and quantities, cancellation rate','Depth, spread, resilience and withdrawal distributions'],['DEX pools','Reserves, fee tier, liquidity distribution, swaps, gas','Executable on-chain depth and price impact'],['Trade tape','Signed trades, volume, timestamps, block / venue','Order-flow intensity and price impact'],['MM arrangements','Funded cash, token inventory, quoted spread/depth, replenishment limits','Determine genuinely committed liquidity'],['Token holders','Vesting wallets, beneficial owners, circulation and locked balances','Unlock sell propensity and concentration'],['Project cash flows','Realized receipts, costs, reserves, defaults, contractual waterfall','Calibrate real yield and credit risk'],['Token price history','Returns, realized volatility, jumps, correlations','Fit stochastic scenarios and validate holdout performance']]))}`;}

function assumptions(){const errors=validate(config),a=launchReadiness(config,state.stress&&!state.stress.scenarios?state.stress:null,state.attacks),b=config.bridge;return title('Assumptions, governance & launch gates','Edit the complete model, inspect its source hierarchy and assess what remains unverified. All material token allocations must be transparent, including the internal legacy conversion capacity.','03 / CONTROLS',btn('Export config JSON','export-config','primary')+btn('Import config JSON','import-config'))+
`<div class="grid g4">${metric('Configuration errors',F(errors.length),errors.length?'Resolve before simulation':'Supply and parameter rules reconcile',errors.length?'bad':'good')}${metric('Model checks passed',F(a.passed),'Not a production approval')}${metric('Failed model checks',F(a.failed),'Includes stress gates when available',a.failed?'bad':'')}${metric('Unverified gates',F(a.unverified),'External evidence required')}</div>`+
(errors.length?notice(errors.map(esc).join('<br>'),'red'):notice('The configuration passes the model’s structural validation. This does not validate the commercial terms, legal rights, real cash flows or launch liquidity.','blue'))+
`<div class="section-label">Launch-readiness gate register</div>${card('Evidence required before production',checksView(a.checks))} `+
`<div class="grid g2" style="margin-top:18px">${card('Bridge and reward assumptions',`<div class="form-grid">${input('Legacy internal cap CCLX','bridge.internalCap',b.internalCap,100000)}${input('Legacy reference value USD','bridge.valuationCap',b.valuationCap,100000)}${input('Eligible legacy supply','bridge.eligibleSupply',b.eligibleSupply,100000)}${input('Registered legacy supply','bridge.registered',b.registered,100000)}${input('Conversion reference price','bridge.referencePrice',b.referencePrice,.005)}${input('Bridge cliff months','bridge.cliff',b.cliff,1)}${input('Bridge linear months','bridge.linear',b.linear,1)}${input('Claim window days','bridge.claimWindow',b.claimWindow,30)}${input('Assumed take-up','bridge.assumedTakeup',b.assumedTakeup,.05)}${input('Per-beneficial-owner cap','bridge.perEntityCap',b.perEntityCap,.01)}${input('Bootstrap APR target','stress.bootstrapTargetAPR',config.stress.bootstrapTargetAPR,.01)}${input('Cash yield share','stress.feeToRewards',config.stress.feeToRewards,.05)}</div><p class="source-note">The internal capacity is a proposal within Team & Founders. Restricted principal and restricted rewards cannot be sold or used as borrowing collateral. Published investor materials must disclose material economic allocations and restrictions.</p>`)}${card('Cash-flow waterfall and model policy',`<div class="form-grid">${input('Risk reserve share','stress.feeToRisk',config.stress.feeToRisk,.05)}${input('Liquidity reserve share','stress.feeToLiquidity',config.stress.feeToLiquidity,.05)}${input('Operations share','stress.feeToOps',config.stress.feeToOps,.05)}${input('Cash buffer USD','stress.cashBuffer',config.stress.cashBuffer,50000)}${input('Risk reserve USD','stress.reserveRisk',config.stress.reserveRisk,50000)}${input('Collateral haircut','stress.collateralHaircut',config.stress.collateralHaircut,.05)}</div><div class="divider"></div>${kv([['Total waterfall allocation',P(sum(['feeToRewards','feeToRisk','feeToLiquidity','feeToOps'].map(k=>config.stress[k])))],['Maximum token supply',M(config.supply)],['Sale allocation',M(allocation(config,'sales'))],['Reward allocation',M(allocation(config,'rewards'))],['Restricted borrowing','Prohibited'],['Unfunded curve rebase','Prohibited']])}<p class="source-note">Cash distributions are based on realized distributable income only. Project losses, reserves and contractual seniority must be implemented and independently reconciled before production.</p>`)}</div>`+
`<div class="section-label">Complete editable configuration</div>${card('JSON editor — advanced parameters',`<p class="card-sub">Every project parameter, token allocation, funding round, liquidity ladder and stress setting can be edited here. Apply validates the complete configuration before replacing it. Changes reset the mock and invalidate previous simulation results.</p><textarea id="config-json" class="code" rows="18" spellcheck="false">${esc(state.rawJSON||JSON.stringify(config,null,2))}</textarea><div class="page-actions">${btn('Validate & apply JSON','apply-json','primary')}${btn('Reset to working defaults','reset-config')}${btn('Download JSON','export-config')}</div>`)} `+
`<div class="section-label">Source hierarchy and open decisions</div>${card('Model provenance',table(['Source','What is used'],[['CCLX Token Condensed v4/v5','Working 200M maximum supply, five financing rounds, 26M rewards and 18% Team & Founders allocation.'],['2 September 2026 workshop','CO2BIT conversion restricted to project collateral; Green Bond terminology Reporting and Transparency; rewards included in proposed CCLX model.'],['Integrated architecture V8','Separate financing contracts, treasury/project accounting, MRV and project-specific pools.'],['Economic Lab','All market prices, liquidity amounts, revenues, default probabilities, APR assumptions and trading behavior are synthetic.']])+`<p class="source-note">Unresolved decisions: exact legal token rights, verified legacy entitlement and valuation, definitive vesting terms, project cash-flow waterfall, receipt architecture, real yield denomination, market-maker commitments, oracle design and security audit. The prototype chooses conservative restrictions where terms remain unsettled; it must not be presented as an approved token contract.</p>`)} `;}

const pages={overview,mock,'curve-lab':curveLab,liquidity,funding,stress,exploits,calibration,assumptions};
function render(){try{$('#root').innerHTML=shell();}catch(e){console.error(e);$('#root').innerHTML=`<div class="boot"><h2>Render error</h2><p>${esc(e.message)}</p><button onclick="location.reload()">Reload</button></div>`;}}
function invalidate(){state.mock=newMock(config);state.stress=null;state.attacks=null;state.imported=null;state.rawJSON='';save();}
function runWorker(all=false){if(state.running)return;const e=validate(config);if(e.length){toast(e.join('; '),true);return;}state.running=true;state.runKind='stress';state.progress=0;render();const worker=makeWorker();state.worker=worker;const id=Date.now();worker.onmessage=ev=>{if(ev.data.id!==id)return;if(ev.data.type==='progress'){state.progress=ev.data.progress;const overlay=$('.progress-overlay');if(overlay){const fill=overlay.querySelector('.progress-fill');if(fill)fill.style.width=P(state.progress,0);const h=overlay.querySelector('.card-head span');if(h)h.textContent=F(state.progress*100)+'%';}}else{state.running=false;state.runKind='';worker.terminate();state.worker=null;if(ev.data.type==='done'){state.stress=ev.data.result;state.stress.assumptions=clone(config);state.page='stress';render();toast('Simulation completed. Results are synthetic and reproducible.');}else{render();toast(ev.data.error,true);}}};worker.onerror=e=>{state.running=false;state.runKind='';worker.terminate();state.worker=null;render();toast(e.message||'Simulation worker failed',true);};worker.postMessage({id,config:clone(config),scenario:SCENARIOS.find(x=>x.id===state.scenario)?.changes||{},all});}
function runCurveWorker(kind='curve-sim'){if(state.running)return;const e=validateCurveConfig(state.curveConfig);if(e.length){toast(e.join('; '),true);return;}state.running=true;state.runKind=kind;state.progress=0;render();const worker=makeWorker();state.worker=worker;const id=Date.now(),scenario=CURVE_LAB_SCENARIOS.find(x=>x.id===state.curveScenario)?.changes||{};worker.onmessage=ev=>{if(ev.data.id!==id)return;if(ev.data.type==='progress'){state.progress=ev.data.progress;const fill=$('.progress-fill');if(fill)fill.style.width=P(state.progress,0);}else{state.running=false;state.runKind='';worker.terminate();state.worker=null;if(ev.data.type==='done'){if(kind==='curve-optimize')state.curveOptimizer=ev.data.result;else state.curveResult=ev.data.result;state.page='curve-lab';state.curveTab=kind==='curve-optimize'?'optimizer':'simulation';render();toast(kind==='curve-optimize'?'Optimization completed.':'Bonding curve simulation completed.');}else{render();toast(ev.data.error||'Curve worker failed',true);}}};worker.onerror=e=>{state.running=false;state.runKind='';worker.terminate();state.worker=null;render();toast(e.message||'Curve worker failed',true);};worker.postMessage({id,kind,config:clone(state.curveConfig),scenario,options:kind==='curve-optimize'?{searchSpace:DEFAULT_SEARCH_SPACE,constraints:DEFAULT_CONSTRAINTS,selectionSeeds:[101,102,103],validationSeeds:[901,902],budget:60}:{seed:state.curveConfig.seed}});}
function doMock(type,args={}){try{state.mock=mockAction(state.mock,config,type,args);render();toast('Mock transaction completed.');}catch(e){toast(e.message,true);}}
function changeConfig(el){try{const path=el.dataset.config;let value=Number(el.value);if(el.dataset.scale)value/=Number(el.dataset.scale);if(!Number.isFinite(value))throw Error('Enter a finite number.');set(path,value);render();toast('Assumption updated. The mock and prior results were reset to keep the model consistent.');}catch(e){render();toast(e.message,true);}}
function applyJSON(text){const next=JSON.parse(text);const errors=validate(next);if(errors.length)throw Error(errors.join('; '));config=next;invalidate();render();toast('Configuration applied. Previous simulation results were invalidated.');}
function handleAction(action){if(action.startsWith('go-'))return navigate(action.slice(3));if(action.startsWith('scenario:')){state.scenario=action.split(':')[1];navigate('stress');return;}
if(action.startsWith('choose-project:')){state.projectId=action.split(':')[1];state.page='mock';render();setTimeout(()=>document.querySelector('.section-label:nth-of-type(3)')?.scrollIntoView({block:'center',behavior:'smooth'}),50);return;}
switch(action){case 'menu':state.sidebar=!state.sidebar;render();return;case 'refresh':render();return;case 'reset-mock':doMock('reset');return;case 'advance-30':doMock('advance',{amount:30});return;case 'advance-365':doMock('advance',{amount:365});return;case 'mock-trade':doMock(state.mockSide,{amount:state.mockAmount,nonce:'demo-'+crypto.randomUUID()});return;
case 'mock-allocate':{const source=$('#allocation-source')?.value||'liquid',amount=Number($('#pool-amount')?.value);state.mockAmount=amount;doMock('allocate',{amount,projectId:state.projectId,restricted:source!=='liquid',source:source==='restrictedRewards'?'reward':source});return;}
case 'mock-withdraw':{const source=$('#allocation-source')?.value||'liquid',amount=Number($('#pool-amount')?.value);state.mockAmount=amount;doMock('withdraw',{amount,projectId:state.projectId,restricted:source!=='liquid'});return;}
case 'mock-claim':doMock('claim');return;case 'mock-verify':doMock('verify',{projectId:state.projectId});return;
case 'run-stress':runWorker();return;case 'run-all':runWorker(true);return;case 'cancel':state.worker?.terminate();state.worker=null;state.running=false;render();toast('Simulation cancelled.');return;
case 'run-curve':runCurveWorker('curve-sim');return;case 'run-curve-optimizer':runCurveWorker('curve-optimize');return;case 'curve-preset-condensed':state.curveConfig=condensedV5Config(config);state.curveProjectId=state.curveConfig.projects[0].id;state.curveResult=null;state.curveOptimizer=null;state.page='curve-lab';state.curveTab='overview';render();toast('condensed_v5 preset loaded with explicit USD→CCLX conversion metadata.');return;case 'curve-reset':state.curveConfig=defaultCurveLabConfig(config);state.curveProjectId='forest';state.curveResult=null;state.curveOptimizer=null;render();toast('Bonding curve lab defaults restored.');return;
case 'reset-stress':{const next=clone(config);next.stress=defaults().stress;config=next;invalidate();render();return;}
case 'run-attacks':state.attacks=runAttackSuite(config);render();toast(`${state.attacks.passed} passed, ${state.attacks.failed} failed, ${state.attacks.unverified} unverified.`);return;
case 'export-config':download('cclx-assumptions.json',JSON.stringify(config,null,2),'application/json');return;
case 'import-config':{const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{applyJSON(await i.files[0].text());}catch(e){toast(e.message,true);}};i.click();return;}
case 'apply-json':{try{const text=$('#config-json').value;applyJSON(text);}catch(e){state.rawJSON=$('#config-json')?.value||'';toast(e.message,true);}return;}
case 'reset-config':if(!confirm('Reset all assumptions and the mock portfolio to the working defaults?'))return;config=defaults();invalidate();render();toast('Working defaults restored.');return;
case 'export-unlocks':{const rows=unlockPressureAudit(config,state.months);download('cclx-unlocks.csv',csv([['month','ordinary_unlocked','restricted_release','expected_sell_tokens','sell_notional_usd','depth_2pct_usd','coverage','required_depth_usd','gap_usd'],...rows.map(r=>[r.month,r.unlocked,r.restricted,r.expectedSell,r.pressure,r.depth,r.coverage,r.requiredDepth,r.gap])]),'text/csv');return;}
case 'export-stress':if(state.stress)download('cclx-stress-results.json',JSON.stringify({assumptions:config,results:state.stress},null,2),'application/json');return;
case 'export-stress-csv':if(state.stress?.series)download('cclx-stress-monthly.csv',csv([['month','price_p05','price_p50','price_p95','depth_p50','unlock_pressure_p50','total_pressure_p50','coverage_p05','coverage_p50','breach_probability','unlock_breach_probability','queue_probability'],...state.stress.series.map(r=>[r.month,r.price.p05,r.price.p50,r.price.p95,r.depth.p50,r.unlockSalesUSD.p50,r.totalPressureUSD.p50,r.coverage.p05,r.coverage.p50,r.failProbability,r.unlockFailProbability,r.queueProbability])]),'text/csv');return;
case 'export-paths':if(state.stress?.pathSummaries){const rows=state.stress.pathSummaries,keys=Object.keys(rows[0]);download('cclx-stress-paths.csv',csv([keys,...rows.map(r=>keys.map(k=>r[k]))]),'text/csv');}return;
case 'export-curve-config':download('cclx-curve-config.json',JSON.stringify(state.curveConfig,null,2),'application/json');return;
case 'export-curve-result':if(state.curveResult)download('cclx-curve-results.json',JSON.stringify(state.curveResult,null,2),'application/json');return;
case 'export-curve-network':if(state.curveResult)download('cclx-curve-network.csv',csv(exportNetworkCSV(state.curveResult)),'text/csv');return;
case 'export-curve-transactions':if(state.curveResult)download('cclx-curve-transactions.csv',csv(exportTransactionsCSV(state.curveResult)),'text/csv');return;
case 'export-curve-report':if(state.curveResult)download('cclx-curve-report.md',exportMarkdownReport(state.curveResult),'text/markdown');return;
case 'export-curve-candidates':if(state.curveOptimizer)download('cclx-optimization-candidates.csv',csv(exportCandidatesCSV(state.curveOptimizer)),'text/csv');return;
case 'download-template':download('cclx-orderbook-template.csv',csv([['side','price','quantity','venue'],['bid',0.2745,100000,'Demo CEX'],['bid',0.2730,150000,'Demo CEX'],['ask',0.2755,100000,'Demo CEX'],['ask',0.2770,150000,'Demo CEX']]),'text/csv');return;
case 'analyze-csv':try{state.imported=analyzeSnapshot(parseOrderBookCSV($('#orderbook-text').value),config);render();toast('Snapshot analyzed. No live exchange data was accessed.');}catch(e){toast(e.message,true);}return;
case 'clear-csv':state.imported=null;render();return;
}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){navigate(nav.dataset.nav);return;}const tab=e.target.closest('[data-curve-tab]');if(tab){state.curveTab=tab.dataset.curveTab;render();return;}const action=e.target.closest('[data-action]');if(action)handleAction(action.dataset.action);const side=e.target.closest('[data-mock-side]');if(side){state.mockSide=side.dataset.mockSide;state.mockAmount=state.mockSide==='convert'?75000:1000;render();}});
document.addEventListener('change',async e=>{const el=e.target;if(el.dataset.config){changeConfig(el);return;}if(el.dataset.curveConfig){try{const path=el.dataset.curveConfig,value=Number(el.value);if(path==='ui.curveQuoteAmount')state.curveQuoteAmount=value;else if(path==='ui.curveWithdrawalShares')state.curveWithdrawalShares=value;else setCurve(path,value);render();toast('Curve lab assumption updated. Prior curve results were invalidated.');}catch(err){render();toast(err.message,true);}return;}if(el.dataset.curveSelect){try{const path=el.dataset.curveSelect;if(path==='curveProject')state.curveProjectId=el.value;else if(path==='curveScenario')state.curveScenario=el.value;else setCurve(path,el.value);render();}catch(err){render();toast(err.message,true);}return;}if(el.id==='mock-amount'||el.id==='pool-amount'){state.mockAmount=Number(el.value);render();return;}if(el.id==='quote-amount'){state.quoteAmount=Number(el.value);render();return;}if(el.id==='quote-side'){state.quoteSide=el.value;render();return;}if(el.id==='stress-scenario'){state.scenario=el.value;render();return;}if(el.id==='orderbook-file'&&el.files?.[0]){try{state.imported=analyzeSnapshot(parseOrderBookCSV(await el.files[0].text()),config);render();toast('Snapshot imported.');}catch(err){toast(err.message,true);}return;}});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(pages[p]&&p!==state.page)navigate(p);});
if(pages[location.hash.slice(1)])state.page=location.hash.slice(1);
render();
