import {clone,bridgeQuote,bridgeClaim,vestFraction,unlockSchedule,allocateRewards,defaults} from './model.js';
import {makeMarket,executeBuy,executeSell,marketDepth,guardedSell} from './market.js';
import {newMock,mockAction} from './mock.js';
import {newVault,curveTrade,curveQuote,curveAudit,rebaseCurve} from './curve.js';
const check=(condition,message)=>{if(!condition)throw Error(message);};
const reject=(fn,pattern)=>{let error;try{fn();}catch(e){error=e;}if(!error||pattern&&!pattern.test(error.message))throw Error('Expected rejection did not occur'+(error?': '+error.message:''));};
export function adversarialEconomics(c){const m=makeMarket(c),trade=Math.min(100000,c.liquidity.cexQuote/3),victim=150000;const baseline=executeBuy(m,victim);const attacker=executeBuy(m,trade,true);const attacked=executeBuy(m,victim,true);const exit=executeSell(m,attacker.tokens,true);const oracle={reference:c.launchPrice,manipulated:c.launchPrice*1.4,collateral:100000,unsafeBorrow:100000*c.launchPrice*1.4*c.stress.borrowLTV,safeBorrow:100000*c.launchPrice*c.stress.borrowLTV,guardedBorrow:100000*c.launchPrice*c.stress.borrowLTV*(1-c.stress.collateralHaircut)};return {sandwich:{attackerSpend:trade,victimSpend:victim,victimBaselineTokens:baseline.tokens,victimAttackedTokens:attacked.tokens,victimLossTokens:baseline.tokens-attacked.tokens,attackerExitUSD:exit.quote,attackerPnL:exit.quote-trade,warning:'Synthetic same-snapshot round trip; ignores gas, MEV competition, external price movement and venue execution constraints.'},oracle,flashStake:{epochBudget:500000,transientStake:1000000,ordinaryStake:100000,unsafeCapture:500000*1000000/1100000,guardedCapture:0,reason:'A time-weighted epoch excludes balances introduced only for the settlement transaction.'}};}
export function runAttackSuite(c){const results=[];const run=(id,name,severity,fn,impact,mitigation)=>{try{const detail=fn();results.push({id,name,severity,status:'pass',detail,impact,mitigation});}catch(e){results.push({id,name,severity,status:'fail',detail:e.message,impact,mitigation});}};
const unverified=(id,name,severity,detail,impact,mitigation)=>results.push({id,name,severity,status:'unverified',detail,impact,mitigation});
run('restricted-sale','Restricted principal cannot enter a sell order','Critical',()=>{const s=newMock(c);s.wallet.restricted=1000;reject(()=>mockAction(s,c,'sell',{amount:1000}),/unrestricted/);return 'Real mock sell action rejects the restricted balance.'},'Up to the restricted principal notional if provenance is lost.','Separate on-chain balance type; transfer hooks and venue allowlists.');
run('withdrawal','Deposit / withdrawal preserves provenance','Critical',()=>{let s=newMock(c);s.wallet.restricted=1000;s=mockAction(s,c,'allocate',{amount:1000,projectId:c.projects[0].id,restricted:true});const pos=s.wallet.positions[0],value=s.vaults[c.projects[0].id].backing*pos.shares/s.vaults[c.projects[0].id].shares;s=mockAction(s,c,'withdraw',{amount:value,projectId:c.projects[0].id,restricted:true});check(s.wallet.liquid===0&&s.wallet.restricted>0,'Provenance changed.');return 'The actual curve exit returns only restricted CCLX, net of the mock fee.'},'All restricted collateral if an exit reclassifies balances.','Typed receipts, restricted withdrawal destinations and conservation assertions.');
run('reward-laundering','Restricted rewards cannot become free CCLX','Critical',()=>{let s=newMock(c);s.wallet.restricted=1000;s=mockAction(s,c,'allocate',{amount:1000,projectId:c.projects[0].id,restricted:true});s=mockAction(s,c,'advance',{amount:30});s=mockAction(s,c,'claim');check(s.wallet.liquid===0&&s.wallet.restrictedRewards>0,'Restricted rewards became free.');reject(()=>mockAction(s,c,'transfer',{amount:1,restricted:true,source:'restrictedRewards'}),/cannot/);return 'Accrued restricted rewards retain their collateral-only type after claim.'},'Reward emissions and legacy principal could become a disguised exit route.','Separate reward provenance; restricted receipt and claim policies.');
run('bridge-cap','Aggregate and beneficial-owner caps','Critical',()=>{const b=clone(c),q=bridgeQuote(b);b.bridge.claimed=q.cap-1;reject(()=>bridgeClaim(b,q.ratio*2),/cap/);const x=clone(c);x.bridge.perEntityCap=.01;reject(()=>bridgeClaim(x,bridgeQuote(x).ratio*bridgeQuote(x).cap*.02),/owner/);return 'Both cap guards reject claims that would exceed the working limits.'},'Working maximum bridge value $3.3M; not a verified market valuation.','Snapshot, fixed ratio, consumed entitlements, aggregate and UBO caps.');
run('replay','Duplicate bridge claim nonce','Critical',()=>{let s=newMock(c);s=mockAction(s,c,'convert',{amount:7500,nonce:'claim-1'});reject(()=>mockAction(s,c,'convert',{amount:7500,nonce:'claim-1'}),/nonce/);return 'The mock ledger consumes a claim nonce before another claim can use it.'},'Duplicate issuance up to the cap if claims are not atomic.','Atomic on-chain claim nullifiers, burn/lock proof and replay protection.');
run('vesting','Cliff and allocation-only release','Critical',()=>{check(vestFraction(11,12,24)===0&&vestFraction(12,12,24)===0&&vestFraction(36,12,24)===1,'Vesting calculation failed.');let s=newMock(c);s=mockAction(s,c,'convert',{amount:75000});s=mockAction(s,c,'advance',{amount:365});check(s.wallet.restricted<1e-6,'Early release.');s=mockAction(s,c,'advance',{amount:365});check(s.wallet.restricted>0&&s.wallet.liquid===0,'Restricted vesting failed.');return 'No release before cliff; subsequent release unlocks allocation rights, not transfers.'},'Premature access to restricted balances.','Immutable vesting logic, audited timestamp math and governance timelocks.');
run('receipt','Receipt transfer, wrapper and pledge isolation','Critical',()=>{let s=newMock(c);s.wallet.restricted=1000;s=mockAction(s,c,'allocate',{amount:1000,projectId:c.projects[0].id,restricted:true});for(const action of ['wrap','receiptTransfer','pledge'])reject(()=>mockAction(s,c,action,{amount:1,restricted:true}),/cannot/);return 'All three actual mock paths reject restricted receipts.'},'Full pledged amount and potential borrowed cash.','Non-transferable receipt contract; reject approvals, permits and composable wrappers.');
run('borrow','Restricted collateral cannot be borrowed against','Critical',()=>{const x=clone(c);x.stress.borrowEnabled=true;let s=newMock(x);s.wallet.restricted=1000;s=mockAction(s,x,'allocate',{amount:1000,projectId:x.projects[0].id,restricted:true});reject(()=>mockAction(s,x,'borrow',{amount:10,projectId:x.projects[0].id,restricted:true}),/prohibited/);return 'Borrowing stays prohibited even if the ordinary borrowing feature is enabled.'},'Borrowed quote currency can bypass principal transfer restrictions.','Hard prohibition on restricted collateral in all lending adapters and liquidations.');
run('curve-solvency','Curve reserve and round-trip invariants','Critical',()=>{const v=newVault(c.projects[0]),before=v.backing;const d=curveTrade(v,10000,'deposit');const w=curveTrade(v,d.shares,'withdraw');check(curveAudit(v).solvent,'Curve lost backing.');check(Math.abs(v.backing-before)<1e-5,'Reserve conservation failed.');check(w.output<=10000+1e-6,'Round trip created collateral.');return 'Buy/mint and redeem/burn preserve reserve backing; fees remain separate.'},'Unfunded redemption obligations or artificial collateral creation.','Reserve conservation, audited arithmetic and explicit funding of parameter changes.');
run('curve-rebase','Milestone cannot mint an unfunded floor','High',()=>{const v=newVault(c.projects[0]);reject(()=>rebaseCurve(v,v.a*1.2,v.b,0),/Unfunded/);return 'Raising the curve intercept without additional backing is rejected.'},'Artificial NAV or implied redemption floor.','Require independent milestone validation and explicit reserve funding.');
run('finite-depth','Large selling consumes finite market liquidity','Critical',()=>{const m=makeMarket(c),before=m.y+marketDepth(m,200).cex;const q=executeSell(m,10e6,true);check(q.quote<10e6*c.launchPrice&&m.y>=0&&marketDepth(m,200).total<before,'Finite-depth invariant failed.');return `10M CCLX sell receives $${q.quote.toFixed(0)}; DEX quote reserve remains $${m.y.toFixed(0)}.`},'Severe impact and possible near-exhaustion of executable quote liquidity.','Slippage guards, finite cash budgets, auction/OTC paths and circuit breakers.');
run('no-phantom-unlocks','Legacy and unissued rewards excluded from sellable unlocks','Critical',()=>{const schedule=unlockSchedule(c,36);check(schedule.every(r=>r.byBucket.bridge>=0&&r.deltas.bridge>=0),'Missing bridge schedule.');check(schedule.every(r=>r.scheduledSellTokens>=0),'Negative unlocks.');const r=schedule[24];check(r.scheduledSellTokens<=r.liquidDelta+1e-6,'Restricted or reward capacity became sellable.');return 'Restricted releases and unissued reward ceilings have no automatic sellable-flow contribution.'},'Overstated liquidity or incorrectly assumed circulating supply.','Separate issued / circulating / restricted / governed / unissued ledgers.');
run('reward-cap','Emission ceiling is enforced','Critical',()=>{const x=clone(c);x.stress.bootstrapTargetAPR=20;const r=allocateRewards(x,0,[1e9,1e9,1e9]);check(r.distributed<=x.rewardBudget[0]/12+1e-5&&r.unused>=-1e-5,'Reward cap exceeded.');return 'Extremely high reward demand is scaled down to the monthly budget.'},'Excess minting or an unfunded advertised APR.','Capped emissions, per-epoch accounting and no promised fixed APR.');
run('double-claim','Rewards cannot be claimed twice','High',()=>{let s=newMock(c);s.wallet.liquid=1000;s=mockAction(s,c,'allocate',{amount:1000,projectId:c.projects[0].id});s=mockAction(s,c,'advance',{amount:30});s=mockAction(s,c,'claim');const first=s.wallet.liquid;s=mockAction(s,c,'claim');check(Math.abs(s.wallet.liquid-first)<1e-8,'Reward replay.');return 'Second claim has no effect on already consumed reward balances.'},'Duplicated reward distributions.','Atomic claim accounting and claim-event reconciliation.');
run('oracle-guard','Borrowing LTV and oracle-deviation controls','High',()=>{const x=clone(c);x.stress.borrowEnabled=true;let s=newMock(x);s.wallet.liquid=10000;s=mockAction(s,x,'allocate',{amount:10000,projectId:x.projects[0].id});reject(()=>mockAction(s,x,'borrow',{amount:10000,projectId:x.projects[0].id}),/LTV/);return 'The mock debt path rejects a loan above the conservative collateral LTV. Live oracle validation remains separate.'},'Overvalued collateral multiplied by borrowing LTV.','Independent oracle feeds, staleness/deviation guards, TWAP and conservative LTV.');
unverified('sybil','Beneficial-owner / Sybil identity linkage','High','No connected KYC/UBO provider. The mock owner ID cannot establish that two wallets share a beneficial owner.','Per-entity cap may be bypassed using linked identities.','Identity verification, UBO aggregation, sanctions screening and claim review.');
unverified('reentrancy','Smart-contract reentrancy and ERC-1155 hooks','Critical','No Solidity contracts or deployed bytecode exist in this lab. JavaScript state tests cannot establish EVM safety.','Collateral theft, double withdrawals or unauthorized transfers.','Contract-level invariant/fuzz tests, formal review and independent audit.');
unverified('oracle-integration','Live oracle manipulation and staleness','High','No production oracle adapters, reference market feeds or on-chain TWAP implementation connected.','Manipulated collateral values and liquidations.','Multi-source oracle, circuit breakers, heartbeat and deviation checks.');
unverified('flashloan','Flash-loan / same-block staking manipulation','High','No blockchain execution layer. Time-weighted rewards are a proposed mitigation, not an audited contract implementation.','Up to an unguarded reward epoch or collateral manipulation exposure.','Time-weighted balances, minimum hold, cooldown and same-block restrictions.');
return {results,passed:results.filter(x=>x.status==='pass').length,failed:results.filter(x=>x.status==='fail').length,unverified:results.filter(x=>x.status==='unverified').length,total:results.length,economics:adversarialEconomics(c),disclaimer:'Synthetic model checks only. A passing test is not a contract audit, legal validation, or proof that a real protocol cannot be exploited.'};}
